Add files via upload

diff --git a/Nemesis/usr/local/save-changesnew/inotify b/Nemesis/usr/local/save-changesnew/inotify
--- a/Nemesis/usr/local/save-changesnew/inotify
+++ b/Nemesis/usr/local/save-changesnew/inotify
@@ -1,31 +1,44 @@
 #!/usr/bin/env bash
-#inotify db3 					01/09/2025
+#inotify db5 					01/17/2026
+#SCRIPT_PATH="$( dirname "$0")"
+#. "$SCRIPT_PATH"/rntchangesfunctions
 . /usr/local/save-changesnew/rntchangesfunctions
 
-# inotify to watching either / or /mnt/live/memory/changes. filters out some files and also browser suppressions in sbwr array
+# inotify to watching either / or /mnt/live/memory/changes. filters out some files and also browser suppressions in sbwr array. see rntchangesfunctions
 # Also filters out app inclusions in inotifyexl array
 # purpose to prepare hashed files that are downloads from a package manager or are copied files that have preserved
 # metadata where ctime is greater than mtime. This is because they would not show up in a regular file search.
 #
-# result bypassing, one of two loops, the ctime loop. Any files over 1MB are cached and are picked up
-# by recentchangessearch app and stored in ctimecache.gpg.
+# result bypassing, one of two loops, the ctime loop. Any files over 1MB are cached for this script and the main search mtime loop
 
-# inclusions from app. also .wh. files that can appear from watchingn changes. possibly want to filter out other files ie share/Trash
+# inclusions from app. also .wh. files that can appear from watching changes. possibly want to filter out other files ie share/Trash
 inotifyexl() {
 inclusion=(
 	'.*/\.wh\.([^/]*)$'
 	".*/Downloads/${LCLMODULENAME}x"
 	"/tmp/${LCLMODULENAME}x"
+	"/tmp/rc/${LCLMODULENAME}_MDY"
 	"/tmp/${LCLMODULENAME}_MDY_[^/]*/${LCLMODULENAME}x.+$"
+	"/usr/local/save-changesnew/flth.csv"
+	"$log_file"
 )
 }
 
+
 #VARS
 #atmp=/tmp/myfld$$
-#tmp_input="/tmp/inotify_input_$$.tmp"
 ch="/mnt/live/memory/changes"
 fmt="%Y-%m-%d %H:%M:%S"
 BRAND=`date +"MDY_%m-%d-%y-TIME_%R"|tr ':' '_'`
+efile="/usr/local/bin/recentchanges"
+
+# These can be user set so call get_inclusions and get form recentchanges script. Below default paths in case cant find
+logpst="/usr/local/save-changesnew/logs.gpg"			;	statpst="/usr/local/save-changesnew/stats.gpg"
+pydbpst="/usr/local/save-changesnew/recent.gpg"		;	email="john.doe@email.com"
+rlt=""
+rltt=""
+rlttt=""
+mail=""
 
 log_file=$1
 LCLMODULENAME="$2"
@@ -37,21 +50,38 @@ time="$7"
 match_found=0
 dpaths=()
 
-:> $CACHE_F ; :> /tmp/output
-echo "$BRAND inoftiy started" >> /tmp/inotify.log
+SECONDS=0
+time_out=160
+retried=0
+LIMIT=3
+sleep_index=0
+sleep_times=(0.125 0.225 0.5 2 4)
+j=${sleep_times[sleep_index]}
+prev_size=-1
+incr=0
+
+debug_log="true"
+debug_file=/tmp/inotify.log
+pblk_log_file=/tmp/output
+
+get_inclusion "$efile"
+
+:> $CACHE_F ; :> $pblk_log_file
+
+echo "$BRAND inoftiy started" >> $debug_file
 
 
 F=(
-	'bin' 
+	'bin'
 	'etc'
 	'home'
-	'lib' 
-	'lib64' 
-	'opt' 
-	'root' 
-	'sbin' 
+	'lib'
+	'lib64'
+	'opt'
+	'root'
+	'sbin'
 	'tmp'
-	'usr' 
+	'usr'
 	'var'
 )
 
@@ -69,17 +99,21 @@ done
 
 sbwr
 inotifyexl
+inclusion+=("$rlt") ; inclusion+=("$rltt") ; inclusion+=("$rlttt")
 
-#changed to -e move from -e moved_to  . misses some kernel optimizations can miss a copy with preserved metadata
-timeout "$time" inotifywait -m -r -e create -e move --format '%w%f%0' "${dpaths[@]}" | while read -r -d '' o; do
+timeout "$time" inotifywait -m -r -e create -e moved_to --format '%e|%w%f%0' "${dpaths[@]}" | while read -r -d '' o; do
+
+    [[ "$debug_log" = "true" ]] && log_date=$(date +"$fmt")
+    event=${o%%|*}
+    o=${o#*|}
 
 	if [[ $abpath != "/" ]]; then o="${o#$ch}" ; fi
 
-    # log_date=$(date +"$fmt")
-	 echo "$log_date processing $o" >> /tmp/inotify.log
+    log_lineout $debug_log $debug_file "$log_date" "File event: $event file: $o"
+
     if [[ -d "$o" ]]; then
-        # echo "$(date +"$fmt") Directory created: $o" >> /tmp/inotify.log
-		# incase the file is created at the same time ie scripts or a process and could be missed by intoify. however during testing -r captures it
+        log_lineout $debug_log $debug_file "$log_date" "Directory created: $o"
+        #incase the file is created at the same time ie scripts or a process and could be missed by intoify. however during testing -r captures it
 		#find "$o" -cmin -5 -not -type d -printf '%T@ %A@ %C@ %i %M %n %s %u %g %m %p\0' |
 		#while IFS= read -r -d '' record; do
 		#	if [[ "$o" =~ \.(tmp|swp|bak|part|crdownload|partial|lock)$ ]]; then continue ; fi  
@@ -87,11 +121,10 @@ timeout "$time" inotifywait -m -r -e create -e move --format '%w%f%0' "${dpaths[
 		#	sblk "$record" "$log_file" "/dev/null" "$checkSUM" "$xMODE" "$CACHE_F"
 		#done
         continue
-    
-    elif [[ -f "$o" && "$o" != *.part ]]; then 
-	 	echo "$log_date inotify found checking for matches $o" >> /tmp/inotify.log  # debug
-        # if [[ "$o" =~ \.(tmp|swp|bak|part|crdownload|partial|lock)$ ]]; then continue ; fi  original
 
+    elif [[ -f "$o" ]]; then 
+        log_lineout $debug_log $debug_file "$log_date" "inotify found checking for matches $o"
+        # if [[ "$o" =~ \.(tmp|swp|bak|part|crdownload|partial|lock)$ ]]; then continue ; fi  original
 		if [[ "$o" == *.* ]]; then
 			ext="${o##*.}"
 			ext="${ext,,}"
@@ -99,7 +132,6 @@ timeout "$time" inotifywait -m -r -e create -e move --format '%w%f%0' "${dpaths[
 				continue
 			fi
 		fi
-
         match_found=0
         for item in "${webb[@]}"; do
             if [[ "$o" =~ $item ]]; then
@@ -107,7 +139,6 @@ timeout "$time" inotifywait -m -r -e create -e move --format '%w%f%0' "${dpaths[
                 break
             fi
         done
-
 		if (( match_found == 0 )); then
 			for item in "${inclusion[@]}"; do
 				if [[ "$o" =~ $item ]]; then
@@ -118,16 +149,42 @@ timeout "$time" inotifywait -m -r -e create -e move --format '%w%f%0' "${dpaths[
 		fi
 
         if (( match_found == 0 )); then
-	 		echo "$log_date inotify matched input to sblk $o" >> /tmp/inotify.log  # debug
-			# Notes: stat --printf="%Y %X %Z %i %A %h %s %U %G %a %n" "$o"  # alternative doesnt print microsecond** 
+
+            log_lineout $debug_log $debug_file "$log_date" "notify matched input to pblk waiting for stable size $o"
+			while (( SECONDS < time_out )); do
+				(( incr++ ))
+				curr_size=$(stat -c %s "$o" 2>/dev/null || echo -1)
+				(( curr_size < 0 )) && break  # Nosuchfile
+				if (( curr_size == prev_size )); then
+					(( retried++ ))
+					[[ $retried -ge $LIMIT ]] && break  # found
+					sleep_index=0
+					j=${sleep_times[0]}
+				else
+					retried=0
+					(( sleep_index < ${#sleep_times[@]} - 1 )) && ((sleep_index++))
+					j=${sleep_times[sleep_index]}
+				fi
+				prev_size="$curr_size" && sleep $j
+			done
+			[[ "$debug_log" = "true" ]] && log_date=$(date +"$fmt")
+			log_lineout $debug_log $debug_file "$log_date" "inotify size stabilized for pblk $o"
+
+            # stat --printf="%y %x %z %i %A %h %s %U %G %a %n" "$o"  # alternative doesnt print microsecond**
+            # y 2026-01-14 00:48:20.527855839
+            # have to parse with date -d "2026-01-14 00:48:20.527855839" +%s.%N 2>/dev/null
 		    { find "$o" -printf "%T@ %A@ %C@ %i %M %n %s %u %g %m %p\0" 2>/dev/null; } |
 		    while IFS= read -r -d '' record; do
-		        [[ -z "$record" ]] && continue
-		        sblk "$record" "$log_file" "/dev/null" "$checkSUM" "$xMODE" "$CACHE_F"
+				[[ -z "$record" ]] && continue
+
+		        pblk "$record" "$log_file" "/dev/null" $checkSUM $xMODE "$CACHE_F" $debug_log "$pblk_log_file"
+
 		    done
+        else
+            log_lineout $debug_log $debug_file "$log_date" "inotify found excluded by matching skipped. for $o"
         fi
-	 elif [[ -f "$o" ]]; then
-	 	echo "$log_date inotify found wrong criteria skipping. for $o" >> /tmp/inotify.log  # debug
+     else
+        log_lineout $debug_log $debug_file "$log_date" "inotify file not found or parsing error. for $o"
     fi
 done
 test -e $log_file && rm $log_file
