Add files via upload

diff --git a/Nemesis/usr/local/save-changesnew/rntchangesfunctions b/Nemesis/usr/local/save-changesnew/rntchangesfunctions
--- a/Nemesis/usr/local/save-changesnew/rntchangesfunctions
+++ b/Nemesis/usr/local/save-changesnew/rntchangesfunctions
@@ -6,8 +6,7 @@ sbwr() {
 webb=(
     'mozilla'
 	'.mozilla'
-    'chromium-ungoogled'
-	#'google-chrome'
+	'chromium-ungoogled'
     "$LCLMODULENAME"
 # other
 )
@@ -21,7 +20,7 @@ function blue(){ echo $txtblue "$1" $rst; }
 }
 postop() {
 if [ "$POSTOP" == "true" ]; then
-	while IFS= read -r x; do x="$(unescf "$x")" ; printf '%s\0' "$x"; done < $1 > $atmpxdata
+	while IFS= read -r x; do x="$(unescf "$x")" ; printf '%s\0' "$x"; done < $1 >> $xdata
     if [ -f $USRDIR/doctrine.tsv ]; then
         sed -i 's/^export POSTOP="true"/export POSTOP="false"/' $2
     else
@@ -39,21 +38,20 @@ if [ "$POSTOP" == "true" ]; then
                 ae=$( stat -c '%X' "$f") ; y=$(date -d "@$ae" +'%Y-%m-%d %H:%M:%S')
                 echo -e "$dt\t$f\t$(( sz / 1024 ))\t$mtyp\t$x\t$y\t$onr" >> $atmp/doctrine
             fi
-        done < $atmpxdata
+        done < $xdata
         unset IFS
         head -1 $atmp/doctrine > $USRDIR/doctrine.tsv
         tail -n +2 $atmp/doctrine | sort -t$'\t' -k7,7 -k3,3n >> $USRDIR/doctrine.tsv
         green "File doctrine.tsv created in $USRDIR"
-        #column -t -s $'\t' $USRDIR/doctrine.tsv      this command prints a nice tab seperated log
     fi
 fi
 }
 stmp() {
 sf=$MODULENAME"_"$FLBRAND
-if (( tmpSRHS > 0 )); then #store it in tmp
+if (( tmpSRHS > 0 )); then
     test -d /tmp/rc || mkdir /tmp/rc
 	r=$(find /tmp/rc -maxdepth 1 -type f -name '*rntfiles_MDY*' 2>/dev/null | wc -l)
-    if [ "$r" -eq "$tmpSRHS" ]; then #Clear last file
+    if [ "$r" -eq "$tmpSRHS" ]; then
         test -f /tmp/rc/full || { touch /tmp/rc/full ; cyan "searches builtup in /tmp/rc"; }
         for file in "/tmp/rc"$MODULENAME"_MDY"*
         do
@@ -71,8 +69,8 @@ local fl=/usr/local/save-changesnew/filter
 test -f $2 || echo "Entry,Hits" >> $2
 sed -n '/^[[:space:]]*#/!s|sed -i '\''/\(.*\)/d'\''.*|\1|p' "$fl" > $lt
 while IFS= read -r pattern; do
-    k=$( echo "$pattern" | sed -e 's/\\//g' -e "s|'\"\${2}\"'|$USR|g") #convert for grep
-    x=$( grep -Fc -- "$k" $1) # search matches from logs
+    k=$( echo "$pattern" | sed -e 's/\\//g' -e "s|'\"\${2}\"'|$USR|g")
+    x=$( grep -Fc -- "$k" $1)
     if grep -Fq "sed -i '/$pattern/d" $2; then
         if (( x > 0 )); then
             y=$( grep -F "sed -i '/$pattern/d" $2 | cut -d',' -f2)
@@ -91,176 +89,107 @@ unset IFS
 rm $lt
 }
 generatekey() {
-	# 5.1 porteus   GPG 2.x+ generate key but if 5.01 has GPG2 do it too
-	if which gpg2 > /dev/null 2>&1 || gpg --version | grep -q "(GnuPG) 2"; then #gpg --full-generate-key
-		read -sp "Enter passphrase for new GPG key: " p
+        read -sp "Enter passphrase for new GPG key: " p
+        echo
 cat > /tmp/keyparams.conf <<EOF
 %echo Generating a GPG key
 Key-Type: RSA
 Key-Length: 4096
 Subkey-Type: RSA
 Subkey-Length: 4096
-Name-Real: John e
+Name-Real: John Doe
 Name-Email: $email
 Expire-Date: 0
 Passphrase: $p
 %commit
 %echo done
 EOF
-		if which gpg2 > /dev/null 2>&1; then
-			gpg2 --batch --pinentry-mode loopback --passphrase "$p" --generate-key /tmp/keyparams.conf
-		else
-			gpg --batch --pinentry-mode loopback --passphrase "$p" --generate-key /tmp/keyparams.conf
-		fi
-		shred -u /tmp/keyparams.conf
-		echo "GPG key generated for ${email}."
-	else
-		if grep -iq "Porteus 5.01" /etc/os-release; then
-			if which expect > /dev/null 2>&1; then # is expect installed?
-				echo "expect needs to be installed. And run the keygen file for 5.01. Remember to remove passphrase after from file."
-			else
-				echo "Please run the keygen file for 5.01. Then erase the passphrase you entered in the file from the file."
-			fi
-		fi
-		return 1
-	fi
+    gpg --batch --pinentry-mode loopback  --passphrase "$p" --generate-key /tmp/keyparams.conf
+    shred -u /tmp/keyparams.conf
+    echo "GPG key generated for ${email}."
 }
 storeenc() {
-shopt -s expand_aliases
 local c
-if [ "$STATPST" == "true" ]; then
-	if which gpg2 > /dev/null 2>&1; then
-		if ! gpg2 --list-keys | grep -q $email; then
-			generatekey
-		fi
-	else
+    if [ "$STATPST" == "true" ]; then
 		if ! gpg --list-keys | grep -q $email; then
 			generatekey
 		fi
-	fi
-	if grep -m 1 -q '^Modified,' $1; then  msg=" stats"; else msg=" log"; fi
-
-	if [ -s "$2" ]; then
-
-		ag="true"
-		if [ "$3" != "dcr" ]; then
-			xdata=$TMPDIR$xdata
-			if ! decrypt $xdata $2; then
-				if [ "$ag" == "false" ]; then
-					echo "Agent not installed for gpg 1.4 skipping... ${msg}"
-				else
-					echo "Failed to decrypt ${2}${msg}"
-				fi
+        if grep -m 1 -q '^Modified,' $1; then msg=" stats"; else msg=" log"; fi
+        if [ -s "$2" ]; then
+			if [ "$3" != "dcr" ]; then
+				xdata=$TMPDIR$xdata
+				if ! decrypt $xdata $2; then
+		            echo "Failed to decrypt  $2$msg"
+		            echo "decrypt $2$msg failed"
+		            return 1
+		        fi
+				source=$xdata
+			else
+				source=$xdata2
+			fi
+			if [ "$msg" == " stats" ]; then
+				declare -A ref_map
+				while IFS= read -r line || [ -n "$line" ]; do
+					key=${line#*,*,*,}
+					[[ -n "$key" ]] && ref_map["$key"]="$line"
+				done < $source
+		        while IFS="" read -r p || [ -n "$p" ]; do
+		            ft=$(echo "$p" | cut -d',' -f1)
+					dt=$(echo "$p" | cut -d',' -f2 | tr -d '"')
+					if [ "$ft" == "Nosuchfile" ]; then #  sed 's/^ *//;s/ *$//')  remove leading trailing space
+						echo "$p" >> $source
+					else
+						ct=$(echo "$p" | cut -d',' -f3 | tr -d '"')
+						filepath=${p#*,*,*,} # format action,"date time","change time", file name 
+						if [[ ! -v ref_map["$filepath"] ]]; then
+				            echo "$p" >> $source
+						else
+						 	found="${ref_map["$filepath"]}"
+							old_dt=$(echo "$found" | cut -d',' -f2 | tr -d '"')
+							old_ct=$(echo "$found" | cut -d',' -f3 | tr -d '"')
+							if [[ "$dt" > "$old_dt" ]] || [[ "$ct" > "$old_ct" ]]; then
+								echo "$p" >> $source
+							fi
+						fi
+					fi
+		        done < $1
+		    else # its a log
+			    c=$( grep -c '^$' $source)
+			    if  (( c == logCT )); then
+			        sed -i '1,/^$/d' $source
+			    fi
+				while IFS= read -r p || [[ -n "$p" ]]; do
+					cFILE=$(sed -E 's/.*"((\\.|[^"])*)".*/\1/' <<< "$p")
+					y=$cFILE
+					current_ln="${p//\"$y\"/}"
+					read -r f1 f2 f3 f4 _  <<< "$current_ln"
+					dt="$f1 $f2"
+					ct="$f3 $f4"
+					r=$( grep -F "$dt \"$y\" $ct" $source)
+					[[ -z "$r" ]] &&  echo "$p" >> $source
+				done < $1
+				unset IFS
+			    echo >> $source # end of log
+		    fi
+            cmmd=(gpg --yes -e -r $email -o $2 $source)
+			if [ "$nc" == "true" ]; then cmmd=(gpg --yes --compress-level 0 -e -r $email -o $2 $source); fi
+			if ! "${cmmd[@]}"; then
+				echo "Encryption failed for file: $source  . $2$msg "
 				return 1
 			fi
-			source=$xdata
-		else
-			source=$xdata2
-		fi
-
-		if [ "$msg" == " stats" ]; then
-			declare -A ref_map
-			while IFS= read -r line || [ -n "$line" ]; do
-				key=${line#*,*,*,}
-				[[ -n "$key" ]] && ref_map["$key"]="$line"
-			done < $source
-         while IFS="" read -r p || [ -n "$p" ]; do
-			ft=$(echo "$p" | cut -d',' -f1)
-			dt=$(echo "$p" | cut -d',' -f2 | tr -d '"')
-			if [ "$ft" == "Nosuchfile" ]; then #  sed 's/^ *//;s/ *$//')  remove leading trailing space
-				echo "$p" >> $source
-			else
-				ct=$(echo "$p" | cut -d',' -f3 | tr -d '"')
-				filepath=${p#*,*,*,} # format action,"date time","change time", file name 
-				if [[ ! -v ref_map["$filepath"] ]]; then
-	                echo "$p" >> $source
-				else
-				 	found="${ref_map["$filepath"]}"
-					old_dt=$(echo "$found" | cut -d',' -f2 | tr -d '"')
-					old_ct=$(echo "$found" | cut -d',' -f3 | tr -d '"')
-					if [[ "$dt" > "$old_dt" ]] || [[ "$ct" > "$old_ct" ]]; then
-						echo "$p" >> $source
-					fi
-				fi
-			fi
-         done < $1
-			unset IFS
-
-		else # its a log
-		    c=$( grep -c '^$' $source)
-		    if  (( c == logCT )); then
-		        sed -i '1,/^$/d' $source
-		    fi
-			while IFS= read -r p || [[ -n "$p" ]]; do
-				cFILE=$(sed -E 's/.*"((\\.|[^"])*)".*/\1/' <<< "$p")
-				y=$cFILE
-				current_ln="${p//\"$y\"/}"
-				read -r f1 f2 f3 f4 _  <<< "$current_ln"
-				dt="$f1 $f2"
-				ct="$f3 $f4"
-				r=$( grep -F "$dt \"$y\" $ct" $source)
-				[[ -z "$r" ]] &&  echo "$p" >> $source
-			done < $1
-			unset IFS
-		    echo >> $source # end of log
-		fi
-
-		t=(--encrypt -r $email -o $2 $source)
-		if which gpg2 > /dev/null 2>&1; then 
-			cmmd=(gpg2 --yes) # 5.01 with 2.0
-		else
-			cmmd=(gpg --yes) # 5.1 with gpg2 or 5.01 with gpg 1.4.23 and gpg agent 2.1.11
-		fi
-		[[ "$nc" == "true" ]] && cmmd+=(--compress-level 0)
-		cmmd+=("${t[@]}")
-		if ! "${cmmd[@]}"; then
-			echo "Encryption failed for file: $source  . $2$msg "
-			return 1
-		fi
-		rm $source #shred -u $source
-		if [ "$msg" == " log" ]; then echo $c; fi
-
-	else # no file create file
-		echo >> $1
-		if which gpg2 > /dev/null 2>&1; then # 5.01 with 2.0
-			if ! gpg2 --yes -e -r $email -o $2 "$1"; then #encrypt
-				 echo "Encryption failed for file: $1"
-				 return 1
-			fi
-		else # 5.1 or 5.01 with 1.4.23
-			if ! gpg --yes -e -r $email -o $2 "$1"; then #encrypt
-				 echo "Encryption failed for file: $1"
-				 return 1
-			fi
-		fi
-		echo "The${msg} was created."
-	fi
-fi
-}
-decrypt() {
-if grep -iq "Porteus 5.01" /etc/os-release && ! which gpg2 > /dev/null 2>&1; then # GnuPG 1.4.23
-    if which gpg-agent > /dev/null 2>&1; then
-	    export GPG_TTY=$(tty)            # If you cant get it to work try commenting these two out and the other two in recentchanges might fix it
-        export GPG_AGENT_INFO=/root/.gnupg/S.gpg-agent:0:1
-	    if ! gpg --yes -d -o $1 $2; then
-		    return 1
-	    fi
-    else
-        ag="false"
-        return 1
+            rm $source
+            if [ "$msg" == " log" ]; then echo $c; fi
+        else
+            echo >> $1
+            if ! gpg --yes -e -r $email -o $2 "$1"; then
+                echo "Encryption failed for file: $1"
+                return 1
+            fi
+            echo "The${msg} was created."
+        fi
     fi
-else # all version with  GPG 2.0
-	if which gpg2 > /dev/null 2>&1; then # porteus 5.01 with v2
-		if ! gpg2 --yes -d -o $1 $2; then
-    		return 1
-		fi
-	else # porteus 5.1 with v2
-		if ! gpg --yes -d -o $1 $2; then
-    		return 1
-		fi
-	fi
-fi
 }
+decrypt(){	if ! gpg --yes -d -o $1 $2; then return 1; fi; }
 iscopy() {
 while IFS= read -r p || [[ -n "$p" ]]; do
     cFILE=$(sed -E 's/.*"((\\.|[^"])*)".*/\1/' <<< "$p")
@@ -615,7 +544,8 @@ fi
 }
 backend() { 
 ofile=/tmpinfo ; tfile=$atmp/tmpd
- TMPDIR=$(mktemp -d $xopt/tmpda.XXXXXX) 
+ TMPDIR=$(mktemp -d $xopt/tmpda.XXXXXX)  
+
 if [ -d /tmp/rc ] && [ "$ANALYTICS" == "true" ] && [ "$STATPST" == "false" ]; then
     for file in /tmp/rc/*; do
         cat $file >> $atmp$ofile 2> /dev/null
@@ -635,6 +565,7 @@ if [ "$STATPST" == "true" ]; then
 			if [ -s $logpst ]; then
 
              # decypt once perform ha and save
+            
              chmod 600 $TMPDIR
              xdata2=$TMPDIR$xdata2
              ofile=$TMPDIR$ofile
@@ -685,8 +616,9 @@ if [ "$STATPST" == "true" ]; then
 				fi
 			fi
 		else
+			cores=""
 			if ! gpg --list-keys | grep -q $email; then generatekey ; fi	
-			python3 /usr/local/save-changesnew/pstsrg.py $SORTCOMPLETE $pydbpst $rout $tfile $checkSUM $cdiag $email $mMODE $ANALYTICSECT $proteusSHIELD $nc $updatehlinks
+			python3 /usr/local/save-changesnew/pstsrg.py $SORTCOMPLETE $pydbpst $rout $tfile $checkSUM $cdiag $email $mMODE $ANALYTICSECT $proteusSHIELD $nc
 			ret=$?
 			pyerrblk
 			processha $argf
