Add files via upload

diff --git a/Nemesis/usr/local/save-changesnew/save-changesnewfnts b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
--- a/Nemesis/usr/local/save-changesnew/save-changesnewfnts
+++ b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
@@ -106,8 +106,8 @@ clog() { tmpdir=$(mktemp -d) && mount -o loop "$1" "$tmpdir" && find "$tmpdir" -
 newxzm() {
 all=() ; keep=()
 while IFS= read -r d; do all+=("$(basename "$d")") ; done < <(find "$ch" -maxdepth 1 -mindepth 1 ) # all folders in changes
-while IFS= read -r l; do [[ -z "$l" ]] && continue ; if [[ "$l" == \** ]]; then echo "$l" ; fi ; done < $EXFILES >> $exclfiles # read patterns from $EXCLUDE ie *share/Trash*
-while IFS= read -r p; do [[ -z "$p" || "$p" =~ ^# ]] && continue ; find "$ch" -path "$ch/$p" -print | sed "s|^$ch/||" ; done < <(cat $trsyncexl $exclfiles) >> $EXFILES # search the wildcards for mksquashfs
+while IFS= read -r l; do [[ -z "$l" ]] && continue ; if [[ "$l" == \** ]]; then echo "$l" ; fi ; done < $EXFILES > $exclfiles # read patterns from $EXCLUDE ie *share/Trash*
+while IFS= read -r p; do [[ -z "$p" || "$p" =~ "^#" ]] && continue ; find "$ch" -path "$ch/$p" -print | sed "s|^$ch/||" ; done < <(cat $trsyncexl $exclfiles ) >> $EXFILES # search the wildcards for mksquashfs
 for d in "${all[@]}"; do # generate all folders to exclude ( our list $FOLDERS anything not in it)
     fd="false"
     for f in $FOLDERS; do
@@ -119,11 +119,11 @@ for d in "${all[@]}"; do # generate all folders to exclude ( our list $FOLDERS a
     if [[ "$fd" == "false" ]]; then keep+=("$d") ; fi
 done
 printf "%s\n" "${keep[@]}" >> "$EXFILES"
-createxzm $1
+createxzm # try
 trlt=$?
-if [ "$trlt" -ne 0 ]; then 
-	echo "Files changed while saving copying to tmp..." ; mkdir $mtmp ; procxzm $1
-    if [ "$FEEDBACK" != "true" ]; then mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $trsyncexl> /dev/null ; else mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $trsyncexl ; fi
+if [ "$trlt" -ne 0 ]; then # or tmp
+	echo "Files changed while saving copying to tmp..." ; mkdir $mtmp ; procxzm $1 # $1 keep .wh.
+    if [ "$FEEDBACK" != "true" ]; then mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $trsyncexl > /dev/null ; else mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $trsyncexl ; fi
 else
     clog "$target$em$rname" $UPDATE ; brnd $UPDATE ; mv $UPDATE $LOGDIR/$LOGFILE # make list
 fi
@@ -132,12 +132,12 @@ if [ "$ANALYTICS" == "true" ]; then end=$(date +%s.%N) ; el=$(awk "BEGIN {print 
 # create _uid_ or _uid_L
 createxzm() {
 cm=(mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $trsyncexl)
-cpt=$( "${cm[@]}" > /dev/null 2> >(grep "changed size while reading") ) # supress stat on .wh.
+cpt=$( "${cm[@]}" 2>&1 >/dev/null | grep "changed size while reading") # supress stat on .wh.
 if [[ -n "$cpt" ]]; then echo "$cpt" ; rm "$target$em$rname" && return 1 ; fi
 }
 run_cmd() { if [ "$FEEDBACK" != "true" ]; then "$@" >>"$UPDATE" 2>/dev/null ; else "$@" | tee -a "$UPDATE" ; fi ; } # see Merge
 procxzm() {
-cd $ch || { mount -o remount,udba=none /; exit; }
+adtcmd=() ; cd $ch || { mount -o remount,udba=none /; exit; }
 if [[ -z "$1" ]]; then
     adtcmd=(-e '*.wh.*') 
     IFS="
@@ -145,7 +145,7 @@ if [[ -z "$1" ]]; then
     for y in $(find $FOLDERS -name ".wh.*"); do
 	    f="${y//.wh./}"
         test -e "$mtmp/$f" && rm -rf "${mtmp:?}/$f";
-        test -e "$INAME/*/$f" || { echo "$y" | fixsqh >> $QEXCL; echo "$y" | fixwh >> $EXCL; echo "$y" >> $EXCLUDED; test -e "$mtmp/$y" && rm -f "$mtmp/$y"; }
+        test -e "$INAME"/*/"$f" || { echo "$y" | fixsqh >> $QEXCL; echo "$y" | fixwh >> $EXCL; echo "$y" >> $EXCLUDED; test -e "$mtmp/$y" && rm -f "$mtmp/$y"; }
     done
     cat $EXCL | unfixwh | fixsqh > $exclfiles   
     test -s $exclfiles && grep -Fvxf $EXFILES $exclfiles > $UPDATE && rm $exclfiles; test -s $UPDATE && cat $UPDATE >> $EXFILES && rm $UPDATE
@@ -157,8 +157,8 @@ if [[ -z "$1" ]]; then
     unset IFS
     find $mtmp -name ".wh.*" -exec rm -r {} \;
     find . -name ".wh.*" ! -name ".wh..*" -exec rm -r {} \;
-fi
-if [[ -s "$EXFILES" ]]; then  base_cmd=(rsync -aHv --exclude-from="$EXFILES" --exclude-from="$trsyncexl") ; else base_cmd=(rsync -aHv --exclude-from="$trsyncexl" ) ; fi #Merge
+fi  # Merge build the command and rsync
+if [[ -s "$EXFILES" ]]; then base_cmd=(rsync -aHv "${adtcmd[@]}" --exclude-from="$EXFILES" --exclude-from="$trsyncexl") ; else base_cmd=(rsync -aHv "${adtcmd[@]}"--exclude-from="$trsyncexl" ) ; fi
 for x in $FOLDERS; do run_cmd "${base_cmd[@]}" "${ch}/${x}/" "$mtmp/${x}/" ; done  
 trlt=$?
 if [ "$trlt" -ne 0 ]; then errmsg "$mtmp" "updating .xzm" ; fi 
@@ -211,7 +211,7 @@ local instm="$1"
 		"${cmd[@]}" > /dev/null 2>&1    
         if [ "$ANALYTICS" == "true" ]; then end=$(date +%s.%N) ; el=$(awk "BEGIN {print $end - $start}") ; fi
     else
-        newxzm
+        newxzm "_uid_L"
     fi
 	if [ "$ROLLBCK" == "true" ]; then
 		if [ -d "${target}${em}/archive/_uid_L" ]; then
@@ -256,6 +256,45 @@ if [ "$r" -gt 0 ]; then
 else
     cyan "no ${src} $1"
 fi
+}
+unpack() {
+for mods in $PWD"/"*_uid_*.xzm; do
+    (( x == 0 )) && { cd $1 || exit ; } ; (( x++ ))
+    [[ "$mods" == *_uid_L* ]] && continue
+    echo $mods >> $oMF
+    dest="/mnt/loop-$(basename "$mods" .xzm)"
+    mkdir $dest
+    if mountpoint -q $dest; then echo "Error: $dest already mounted. Everything preserved."; exit 1; fi
+   if [ ! -f "$mods" ]; then echo "Error: In wrong directory. '$mods' not found."; exit 1; fi
+    mount -o loop $mods $dest
+    IFS="
+    "
+    for y in $(find "${dest}/" -name ".wh.*"); do
+      f="$(echo $y | sed -e "s^${dest}/^^g" -e 's@\.wh\.@@g')"
+      test -e "$f" && rm -rf "$f";
+      #test -e "$INAME/*/$f" || test -e "$y" && rm -f "$y" # <--- wont work || { echo "y" | fixsqh >> $EXCL; echo "$y" >> $EXFILES; test -e "$y" && rm -f "$y"; }
+    done
+    unset IFS
+    cp -aufv $dest/* $1 2> >(tee /tmp/error.log >&2)
+    if [ $? -ne 0 ]; then
+        if grep -v '\.wh\.' /tmp/error.log > /dev/null; then
+            red "Error processing one of the modules ${mods}"
+            cyan "Everything preserved. Check the script and try again. check /tmp/error.log"
+            umount $dest
+            rm -rf $dest
+            rm $oMF
+            rm -rf $1
+            exit 1
+        else
+            cyan "White out file detected and processed"  >&2
+        fi
+    fi
+    umount $dest
+    rm -rf $dest
+done
+unset IFS
+find . -name ".wh.*" -exec rm -r {} \; # works
+cd $pst
 }
 rand_alpha() { letters=( {A..Z} {a..z} ); echo -n "${letters[RANDOM % 52]}${letters[RANDOM % 52]}" ; }
 loadermsg() { green "Updated bootloader in /syslinux/"; cyan "if you use a different loader use cheatcode extramod=${target}${em} include changes modules" ; }
