Add files via upload

diff --git a/Nemesis/usr/local/save-changesnew/save-changesnewfnts b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
--- a/Nemesis/usr/local/save-changesnew/save-changesnewfnts
+++ b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
@@ -1,5 +1,5 @@
 #!/bin/bash
-# save-changesnew functions to move options further up the script             01/09/2026
+# save-changesnew functions to move options further up the script             03/02/2026
 . /usr/local/save-changesnew/mergemodulesfunctions
 dycmb() {
 TFLD=""
@@ -96,7 +96,9 @@ errmsg() { mount -o remount,udba=none / ; if [ "$1" != "false" ]; then test -d "
 errblk() { [[ "$trlt" -ne 0 ]] && errmsg "$mtmp" "$2" ; }
 # Find out the files that have changed with dry run
 createlog() {
-rsync -an --out-format="%f" "$1/" "$2" --exclude '.wh.*' --exclude-from=$EXFILES | sed "s|^$1/||" > $3 # what changed
+cmd=(rsync)
+if [ "$checkSUM" == "true" ]; then cmd+=(-anc) ; else cmd+=(-an) ; fi
+"${cmd[@]}" --out-format="%f" "$1/" "$2" --exclude '.wh.*' --exclude-from=$EXFILES | sed "s|^$1/||" > $3 # what changed  # --out-format="%n" "$1/" "$2" --exclude '.wh.*' --exclude-from=$EXFILES > $3
 rsync -anv "$1/" "$2" --exclude '.wh.*' --exclude-from=$EXFILES > $4 # rsync log
 }
 # Labelling before making .xzm from $ch
@@ -115,21 +117,21 @@ local u=0 ; local rlt=0
 local keep=$tmp/outfile  # perishable
 local remove=$tmp/deletre  # ..
 local aend astart firstsv lswitch tfile
-local mt h
+local mt
 local is_merge="true"
 candidates=() ; mdlnames=()
-override="true"  # dont shift as experimental only used in merge scripts
+
 output=""
 # starting in $target$em saved to $pst
 # Apply write forward merging (guardian) to save writes. More can go wrong implemented guardian for logic
-# h=$(find $target$em -type f -name '*_uid_*.xzm' ! -name '*_uid_L*' -print0 | xargs -0 -r ls -t | head -n 1)  # newest.  ls -tr oldest
+# h=$(find $target$em -type f -name '*_uid_*.xzm' ! -name '*_uid_L*' -exec ls -t {} + | head -n 1)  # newest.  ls -tr oldest # -print0 | xargs -0 -r ls -t | head -n 1
 if [[ -f /dev/shm/xsc ]]; then
 	if [[ "$mdlMRGPRF" = "forward" ]]; then
 		u=$(find . -maxdepth 1 -type f -name '*_uid_*.xzm' ! -name '*_uid_L*' | wc -l)
 	fi
 	if (( u > mdllmt)); then
 		echo "Hit module merge limit merging on write forward"
-		resolve_conflict "_uid_" "*.xzm" ".xzm" ".bak" $is_moved $oMF
+		resolve_conflict "_uid_" "*.xzm" ".xzm" ".bak"
         lswitch="true"
 		is_available "*_uid_*.xzm" $target$em "/tmp" $is_moved $lswitch
 		ret=$?
@@ -184,37 +186,41 @@ if [[ -f /dev/shm/xsc ]]; then
 			package_xzm $mtmp $keepMRGED $elog $is_routine $is_merge $output
 			is_rollback $mtmp "_uid_" $ROLLBCK $ROLLSUMRY $archLMT $is_routine
 			test -e $SFILES && rm $SFILES
-			echo "$target$em/$rname" > /dev/shm/xsc
+			echo "${target}${em}/${rname}" > /dev/shm/xsc
 		fi
     # normal saving
 	else
 		if [ "$ANALYTICS" == "true" ] && [ "$ANALYTICSECT" == "true" ]; then astart=$(date +%s.%N); fi
 		cd $mtmp || exit
 		tfile=$( cat /dev/shm/xsc)
-		if [ ! -f $tfile ]; then  # use the first since boot failing that use h (newest) from above
+		if [ ! -f "$tfile" ]; then  # use the first since boot failing that use h (newest) from above
 			echo "Couldnt find last save point looking for next closest"
 			goahead="false"
 			firstsv=""
 			srt_time_epoch=$(date -d "$(uptime -s)" +%s)
 			while IFS= read -r -d '' file; do
 				(( t++ ))
-		        if (( c == 0 )); then
-		            if (( mt > srt_time_epoch )); then
-		                c=$t
-		                tfile=$file
-		            fi
-		        fi
+				mt=$(stat -c %Y "$file")
+                if (( c == 0 )); then
+                    if (( mt > srt_time_epoch )); then
+                        c=$t
+                        tfile=$file
+                    fi
+                fi
+
 			done < <( find "$target$em" -type f -name '*_uid_*.xzm' ! -name '*_uid_L*' -print0 | sort -z)
 			unset IFS
-			if [ -f "$h" ]; then
+			if [ -n "$firstsv" ]; then h=$firstsv ; fi
+			if [ -f "$tfile" ]; then
 				(( c > 0 && c == t )) && echo Merging single module
 				goahead="true"
 				echo "$tfile" > /dev/shm/xsc
 			fi
 		fi
+
 		# extract all modules to tmpfs to build what files we have since boot
 		if [[ "$goahead" = "true" ]]; then
-			for mods in "$target$em/"*_uid_*.xzm; do 
+			for mods in "${target}${em}/"*_uid_*.xzm; do 
 				[[ "$mods" == *_uid_L* || ! -f "$mods" ]] && continue
 			    if (( r == 0 )); then
 			        if [ "$mods" == "$tfile" ]; then
@@ -223,18 +229,27 @@ if [[ -f /dev/shm/xsc ]]; then
 			    fi
 			    if (( r )); then
 					startmnt $is_merge
-					mount -o loop $mods $dest
+					if ! mount -o loop "$mods" "$dest"; then
+						goahead="false"
+						mount -o remount,udba=none / ; clear_mnt
+						echo "Failed to mount module: $mods use umount $dest and remove the folder to continue"
+						return 1
+					fi
+
+					find "$dest/" -type f -name '.wh.*' -printf '%P\n' > $tmp/whmarkers
 					rsync -a "$dest/" "$tmp" --exclude '.wh.*'
 					rlt=$?
 					if [ "$rlt" -ne 0 ]; then 
-						mount -o remount,udba=none /
-						test -d "$tmp" && rm -rf ${tmp:?} ; clear_mnt
-						echo "failed to extract in newuid(). if unable resolve remove /dev/shm/xsc" && exit 1
+						goahead="false"
+						mount -o remount,udba=none / ; clear_mnt
+						echo "failed to extract in newuid(). if unable resolve remove /dev/shm/xsc"
+						return 1
 					fi
 					clear_mnt
 			    fi
 			done
 		fi
+
 		aend=$(date +%s.%N)
 		if [ "$ANALYTICS" == "true" ] && [ "$ANALYTICSECT" == "true" ]; then elapse=$( awk "BEGIN {print $aend - $astart}"); fi
         # save changes into seperate directory
@@ -242,22 +257,50 @@ if [[ -f /dev/shm/xsc ]]; then
 		trlt=$?
 		errblk "$mtmp"
 		test -e $LOGDIR/$LOGFILE && rm $LOGDIR/$LOGFILE  # dont exclude the log file
-		find $mtmp -type f -printf '%P\n' > $tmp/contents
+		find $mtmp -type f -printf '%P\n' > $tmp/contents  # the changes
 
         # what would be transfered then infer what to exclude with rsync dryrun
-		createlog $mtmp $tmp $UPDATE $oMF
+		createlog $mtmp $tmp $UPDATE $oMF 
 
-		c="${mtmp#/}"  # --out-format="%f" consistent log depends on version of rsync ** important
+		 # --out-format="%f" consistent log depends on version of rsync ** important
+		c="${mtmp#/}" 
 		sed -i -e "\|$c/\.|d" -e "s|$c/||" -e '/^\./d' $UPDATE  # remove the unusable first line  .
 		cp $UPDATE $keep
 
-		cat $tmp/contents | grep -Fvf $keep > $remove # the changes folder - what would be transfered = remove
-		cat $remove >> $EXFILES
+        # --out-format="%n" using relative
+		#sed -i -e '/^\./d' -e '/\/$/d' $UPDATE # remove the unusable first line  . and any ending in /
+		#cp $UPDATE $keep  # what needs to be transfered with usable paths
+
+		cat $tmp/contents | grep -Fxvf $keep > $remove # the changes folder - what would be transfered = remove
+		cat $remove >> $EXFILES # exclude these
 
 		labelmk $oMF # copy\insert log before .xzm
 
+        # on subsequent runs compare to the most recent extracted the .wh. so not including duplicate .wh.
+        # if whmarkers is unavailable fall back
+        shopt -s nullglob
+        while IFS= read -r -d '' file; do
+
+            if [[ -e "$tmp"/whmarkers ]]; then
+                grep -Fxq -- "$file" "$tmp"/whmarkers || echo "$file" >> $EXFILES
+            else
+                k="$( echo "$file" | sed -e 's/\.wh\.//g')"  # k=$( echo "$file" | sed -E 's|(.*\/)\.wh\.|\1|') # alternative
+                found="false"
+                items=( "$INAME"/*/"$k" )
+                if ((${#items[@]})); then found="true" ; fi
+                test -e "$tmp/$k" && found="true"
+                [[ "$found" = "true" ]] || echo "$file" >> $EXFILES
+            fi
+        done < <(find "$ch/" -type f -name '.wh.*' -printf '%P\0')
+        shopt -u nullglob
+
+        # cp $tmp/contents /home/guest/contents  # debug
+        # cp $keep /home/guest/keep  # debug
+		# cp $EXFILES /home/guest/excludes  # debug
+		# mksquashfs $ch /mnt/sda3/changes.xzm -comp $cmode -ef $EXFILES  # debug
+
 		# mksquashfs $ch /tmp/megar.xzm -comp $cmode -ef $EXFILES  debug
-		base_cmd=(mksquashfs $ch "$target$em/$rname" -comp $cmode -ef $EXFILES)  
+		base_cmd=(mksquashfs $ch "$target$em/$rname" -comp $cmode -ef $EXFILES)
 		# [[ -s "$QEXCL" ]] && base_cmd+=(-ef $QEXCL)  # add excluded .wh. to EXFILES if needed
 		if [ "$FEEDBACK" != "true" ]; then "${base_cmd[@]}" > /dev/null ; else "${base_cmd[@]}" ; fi
 		if [ "$goahead" == "false" ]; then echo "$target$em/$rname" > /dev/shm/xsc ; fi
@@ -298,7 +341,7 @@ while IFS= read -r l; do [[ -z "$l" ]] && continue ; if [[ "$l" == \** ]]; then 
 # $trsyncexl is excld.ini. 
 # $exclfiles our patterns from $EXCLUDE
 # Instead of sed can use  -printf '%P\n'  <--- works
-while IFS= read -r p; do [[ -z "$p" || "$p" =~ ^# ]] && continue ; find "$ch" -path "$ch"/$p \( -type f -o -type d \) -print | sed "s|^$ch/||" ; done < <(cat $trsyncexl $exclfiles ) >> $EXFILES  # search the wildcards for mksquashfs
+while IFS= read -r p; do [[ -z "$p" || "$p" =~ ^# ]] && continue ; find "$ch" -path "$ch/$p" \( -type f -o -type d \) -print | sed "s|^$ch/||" ; done < <(cat $trsyncexl $exclfiles ) >> $EXFILES  # search the wildcards for mksquashfs
 # all base folders in changes
 while IFS= read -r d; do all+=("$(basename "$d")") ; done < <(find "$ch" -maxdepth 1 -mindepth 1 ) # ! -name ".wh.*"  
 unset IFS 
@@ -325,7 +368,7 @@ else
 	    echo "Files changed while saving copying to tmp..."
         cp $QEXCL $EXFILES # reset exclusions for rsync
 		normalop="false"
-        procxzm $normalop  # copy log and exclude with rsync.
+        procxzm $normalop "false" # copy log and exclude with rsync.
 	    base_cmd=(mksquashfs $mtmp "${target}${em}/${rname}" -comp $cmode)  # make the module
         if [ "$FEEDBACK" != "true" ]; then "${base_cmd[@]}" > /dev/null ; else "${base_cmd[@]}" ; fi
     fi
@@ -373,7 +416,7 @@ if [[ "$1" = "true" ]]; then
 	shopt -u nullglob
     { test -s "$EXCL" && find $FOLDERS -type d | egrep -vf $EXCL || find $FOLDERS -type d; } > $SFOLDERS
 	for y in $(find $mtmp -name ".wh.*"); do
-        f="$(echo "$y" | sed -e "s^$mtmp^^g" -e 's^\.wh\.^^g')"
+        f="$(echo "$y" | sed -e "s|^$mtmp/||g" -e 's|\.wh\.||g')"
         test -e "$f" && rm "$y";
     done
     unset IFS
@@ -382,22 +425,18 @@ fi
 # _uid_ or _uid_L
 base_cmd=(rsync -aHv "${adtcmd[@]}" --exclude-from=$trsyncexl) && [[ -s "$EXFILES" ]] && base_cmd+=(--exclude-from=$EXFILES)
 run_cmd "${base_cmd[@]}" $FOLDERS "$mtmp/" ; errblk "$mtmp"  # merge
+
 # could be new exclusions
 # -mindepth 1 so doesnt list $mtmp itself
-if [[ "$mrgAEX" = "true" ]]; then 
-    cd $mtmp || { mount -o remount,udba=none /; exit; }
-    while IFS= read -r ex; do 
-        [ -n "$ex" ] || continue
+if [[ "$mrgAEX" = "true" && -z "$2" ]]; then
+    cd "$mtmp" || { mount -o remount,udba=none /; exit; }
+    while IFS= read -r ex; do
+        [[ -z "$ex" || "$ex" == \#* ]] && continue
         ex="${ex%/}"
-		# remove dir excludes
-        if [[ "$ex" == */* ]]; then 
-            find "$mtmp" -mindepth 1 -path "$mtmp/$ex" -exec rm -rf -- {} +
-		# pattern glob
-        else 
-            find "$mtmp" -mindepth 1 -name "$ex" -exec rm -rf -- {} + 
-        fi 
-    done < <(cat "$trsyncexl" "$EXFILES") 
+        find "$mtmp" -mindepth 1 -path "$mtmp/$ex" -exec rm -rf -- {} +
+    done < <(cat "$trsyncexl" "$EXFILES")
 fi
+
 brnd $UPDATE
 label
 }
