Add files via upload

diff --git a/Nemesis/usr/local/save-changesnew/save-changesnewfnts b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
--- a/Nemesis/usr/local/save-changesnew/save-changesnewfnts
+++ b/Nemesis/usr/local/save-changesnew/save-changesnewfnts
@@ -74,24 +74,14 @@ fi
 echo  "END ORIGINAL FILES $(date +"%m-%d-%y_%R")" >> "${target}${rlt}${MODULENM}.bak.log"
 nLOG="true"
 }
-autosave() {
-if [[ "$autobackup" == "true" ]] && { [[ "$bck" == "yes" ]] || [[ "$bck" == "y" ]] ; } ; then
-	z=$( grep -Fm 1 "USR" $chc | awk -F'"' '{print $2}')
-	[[ -z "$z" ]] && sed -i "s/USR=.*/USR=\"$USR\"/g" $chc  
-	zz=$( grep -Fm 1 "target" $chc | awk -F'"' '{print $2}')
-	[[ -z "${zz}" ]] && sed -i "s|target=.*|target=\"$target\"|g" $chc   
-	#r=$( basename "$0") ; val="$r \"$target\" \"$USR\""
-	#if ! grep -q "$r" $chc; then 
-	#	sed -i "4i $val" $chc
-	#else
-	#p=$( grep -Fn "$r" $chc | cut -d: -f1) ; lnc=$( grep "$r" $chc | awk -F'"' '{print $2}')
-    #if [ "$lnc" == "" ]; then sed -i "${p}c $val" $chc ; fi # only once
-	#fi
-    [[ ! -x $chc ]] && chmod +x $chc
-else 
-    [[ -x $chc ]] && chmod -x $chc
-fi
-}
+autosave() { if [[ "$autobackup" == "true" ]] && { [[ "$bck" == "yes" ]] || [[ "$bck" == "y" ]] ; } ; then z=$( grep -Fm 1 "USR" $chc | awk -F'"' '{print $2}') ; [[ -z "$z" ]] && sed -i "s/USR=.*/USR=\"$USR\"/g" $chc ; zz=$( grep -Fm 1 "target" $chc | awk -F'"' '{print $2}') ; [[ -z "${zz}" ]] && sed -i "s|target=.*|target=\"$target\"|g" $chc ; [[ ! -x $chc ]] && chmod +x $chc ; else [[ -x $chc ]] && chmod -x $chc ; fi ; }
+#r=$( basename "$0") ; val="$r \"$target\" \"$USR\""
+#if ! grep -q "$r" $chc; then 
+#	sed -i "4i $val" $chc
+#else
+#p=$( grep -Fn "$r" $chc | cut -d: -f1) ; lnc=$( grep "$r" $chc | awk -F'"' '{print $2}')
+#if [ "$lnc" == "" ]; then sed -i "${p}c $val" $chc ; fi # only once
+#fi
 brnd() { BRAND=`date +"MDY_%m-%d-%y-TIME_%R"|tr ':' '_'` ; echo $BRAND >> $1 ; }
 errmsg() {
 mount -o remount,udba=none /
@@ -100,49 +90,47 @@ red "Error making the new module in ${instm}: ${2}" >&2
 cyan "Everything preserved.  Check the script"
 exit 1
 }
-# print contents of new .xzm
-clog() { tmpdir=$(mktemp -d) && mount -o loop "$1" "$tmpdir" && find "$tmpdir" -type f -printf '%P\n' >> "$2" && umount "$tmpdir" && rmdir "$tmpdir" ; }
+clog() { tmpdir=$(mktemp -d) && mount -o loop "$1" "$tmpdir" && find "$tmpdir" -type f -printf '%P\n' >> "$2" && umount "$tmpdir" && rmdir "$tmpdir" ; } # print contents of new .xzm
 # try the fast way. If file changes copy to mtmp to freeze fs
 newxzm() {
 all=() ; keep=()
 while IFS= read -r d; do all+=("$(basename "$d")") ; done < <(find "$ch" -maxdepth 1 -mindepth 1 ) # all folders in changes
 while IFS= read -r l; do [[ -z "$l" ]] && continue ; if [[ "$l" == \** ]]; then echo "$l" ; fi ; done < $EXFILES > $exclfiles # read patterns from $EXCLUDE ie *share/Trash*
 while IFS= read -r p; do [[ -z "$p" || "$p" =~ "^#" ]] && continue ; find "$ch" -path "$ch/$p" -print | sed "s|^$ch/||" ; done < <(cat $trsyncexl $exclfiles ) >> $EXFILES # search the wildcards for mksquashfs
-for d in "${all[@]}"; do # generate all folders to exclude ( our list $FOLDERS anything not in it)
-    fd="false"
-    for f in $FOLDERS; do if [[ "$d" == "$f" ]]; then fd="true" ; break ; fi ; done
-    [[ "$fd" == "false" ]] && keep+=("$d")
-done
+for d in "${all[@]}"; do fd="false" ; for f in $FOLDERS; do [[ "$d" == "$f" ]]  && fd="true" && break ; done ; [[ "$fd" == "false" ]] && keep+=("$d") ; done # generate all folders to exclude ( our list $FOLDERS anything not in it)
 printf "%s\n" "${keep[@]}" >> "$EXFILES"
-createxzm $1 # try
-trlt=$?
+createxzm
+trlt=$? # try
 if [ "$trlt" -ne 0 ]; then # or tmp
-	echo "Files changed while saving copying to tmp..." ; mkdir $mtmp ; procxzm $1 # $1 keep .wh.
-    if [ "$FEEDBACK" != "true" ]; then mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $exclfiles > /dev/null ; else mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $exclfiles ; fi
+    test -e "$target$em$rname" && rm "$target$em$rname"
+	echo "Files changed while saving copying to tmp..." ; mkdir $tmp ; mkdir $mtmp ; procxzm $1
+    find $ch -type f -printf '%P\0' | while IFS= read -r -d '' f; do echo "$f" ; done > $exclfiles # We need to insert the .wh.* files
+    sed -i '/^\.wh\./d' $exclfiles
+	base_cmd=(mksquashfs $ch $tmp$rname -comp $cmode -ef $exclfiles) ; "${base_cmd[@]}" > /dev/null # only .wh.*
+	test -e $tmp$rname && xzm2dir $tmp$rname $mtmp 2> /dev/null && $tmp$rname # insert
+    test -e $exclfiles && rm $exclfiles 
+	base_cmd=(mksquashfs $mtmp "$target$em$rname" -comp $cmode)
+    if [ "$FEEDBACK" != "true" ]; then "${base_cmd[@]}" > /dev/null ; else "${base_cmd[@]}" ; fi
 else
     clog "$target$em$rname" $UPDATE ; brnd $UPDATE ; mv $UPDATE $LOGDIR/$LOGFILE # make list
 fi
-rm $exclfiles
+test -e $exclfiles && rm $exclfiles
 if [ "$ANALYTICS" == "true" ]; then end=$(date +%s.%N) ; el=$(awk "BEGIN {print $end - $start}") ; fi
 }
 # create _uid_ or _uid_L
-createxzm() {
-if [ "$1" == "_uid_L" ]; then  cat $trsyncexl > $exclfiles ; else cat $trsyncexl | grep -v "*.wh..*" > $exclfiles  ; fi # include .wh. and .wh.. for _uid_
-cm=(mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES -ef $exclfiles)
-cpt=$( "${cm[@]}" 2>&1 >/dev/null | grep "changed size while reading") # supress stat on .wh.
-if [[ -n "$cpt" ]]; then echo "$cpt" ; rm "$target$em$rname" && return 1 ; fi
-}
+createxzm() { cm=(mksquashfs $ch "$target$em$rname" -comp $cmode -ef $EXFILES) ; cpt=$( "${cm[@]}" 2>&1 | grep "changed size while reading" ) ; if [[ -n "$cpt" ]]; then echo "$cpt" ; rm "$target$em$rname" ; return 1 ; fi ; } 
+#supress stat on .wh. for user
+#if [ "$1" == "_uid_L" ]; then cat $trsyncexl > $exclfiles ; else cat $trsyncexl | grep -v "*.wh..*" > $exclfiles  ; fi # include .wh. and .wh.. for _uid_
 run_cmd() { if [ "$FEEDBACK" != "true" ]; then "$@" >>"$UPDATE" 2>/dev/null ; else "$@" | tee -a "$UPDATE" ; fi ; } # see Merge
 procxzm() {
-adtcmd=() ; cd $ch || { mount -o remount,udba=none /; exit; }
+adtcmd=(--exclude '.wh.*') ; cd $ch || { mount -o remount,udba=none /; exit; }
 if [[ -z "$1" ]]; then
-    adtcmd=(--exclude '.wh.*') 
     IFS="
     "
     for y in $(find $FOLDERS -name ".wh.*"); do
 	    f="${y//.wh./}"
         test -e "$mtmp/$f" && rm -rf "${mtmp:?}/$f";
-        test -e "$INAME"/*/"$f" || { echo "$y" | fixwh >> $EXCL; echo "$y" >> $EXCLUDED; test -e "$mtmp/$y" && rm -f "$mtmp/$y"; }   # | fixsqh >> $QEXCL; echo "$y"
+        test -e "$INAME"/*/"$f" || { echo "$y" | fixwh >> $EXCL; echo "$y" >> $EXCLUDED; test -e "$mtmp/$y" && rm -f "$mtmp/$y"; }  #  | fixsqh >> $QEXCL; echo "$y" 
     done
     #cat $EXCL | unfixwh | fixsqh > $exclfiles   
     #test -s $exclfiles && grep -Fvxf $EXFILES $exclfiles > $UPDATE && rm $exclfiles; test -s $UPDATE && cat $UPDATE >> $EXFILES && rm $UPDATE
@@ -154,12 +142,13 @@ if [[ -z "$1" ]]; then
     unset IFS
     find $mtmp -name ".wh.*" -exec rm -r {} \;
     #find . -name ".wh.*" ! -name ".wh..*" -exec rm -r {} \;
-fi  # Merge build the command and rsync
-if [[ -s "$EXFILES" ]]; then base_cmd=(rsync -aHv "${adtcmd[@]}" --exclude-from="$EXFILES" --exclude-from="$trsyncexl") ; else base_cmd=(rsync -aHv "${adtcmd[@]}"--exclude-from="$trsyncexl" ) ; fi
+fi  
+base_cmd=(rsync -aHv "${adtcmd[@]}" --exclude-from=$trsyncexl)
+[[ -s "$EXFILES" ]] && base_cmd+=(--exclude-from=$EXFILES) # Merge build the command and rsync
 for x in $FOLDERS; do run_cmd "${base_cmd[@]}" "${ch}/${x}/" "$mtmp/${x}/" ; done  
 trlt=$?
-if [ "$trlt" -ne 0 ]; then errmsg "$mtmp" "updating .xzm" ; fi 
-# Remove if any new exclusions.
+[[ "$trlt" -ne 0 ]] && errmsg "$mtmp" "updating .xzm" 
+# Remove exclusions as there could be new ones
 if [[ -z "$1" ]]; then cd $mtmp || exit ; while IFS= read -r ex; do [ -n "$ex" ] || continue ; ex="${ex%/}"  ; if [[ "$ex" == */* ]]; then find "$mtmp" -mindepth 1 -path "$mtmp/$ex" -exec rm -rf -- {} + ; else find "$mtmp" -mindepth 1 -name "$ex" -exec rm -rf -- {} + ; fi done < <(cat "$trsyncexl" "$EXFILES") ; fi
 brnd $UPDATE
 if [ "$linkedLOGPRF" == "full" ]; then
@@ -174,15 +163,12 @@ createlmdl () {
 local instm="$1"
     if [ "$instm" != "nolmdl" ]; then
         mkdir $mtmp
-        for mods in "$target$em/"*_uid_L*.xzm; do
-            if [ "$fname" == "" ]; then fname="$mods"; fi
-            if ! xzm2dir $mods $mtmp; then errmsg $mtmp "$fname" ; fi
-        done
+        for mods in "$target$em/"*_uid_L*.xzm; do [[ "$fname" == "" ]] && fname="$mods" ; if ! xzm2dir $mods $mtmp; then errmsg $mtmp "$fname" ; fi ; done
 	    procxzm
     fi
     if [ "$ssbn" == "" ]; then
         if [ "$validrlt" == "false" ]; then cyan "mfile byte match failed generating new serial no." ; else cyan "no msr file. creating new one and new serial." ; fi
-        ssbn=$(rand_alpha)$$$(printf "%02d" $((RANDOM % 100)))
+        ssbn=$(rand_alpha)${$}$(printf "%02d" $((RANDOM % 100)))
     fi
     if [ "$rlt" == "true" ]; then
         if [ "$validrlt" == "false" ]; then
@@ -243,7 +229,7 @@ local instm="$1"
 renmmdl() {
 local oMF=/tmp/flog.log ; local drt=$2
 [[ -z "$drt" ]] && src=".bak" && dst=".xzm"
-[[ -n "$drt" ]] && [[ "$drt" == "-r" ]] && src=".xzm" && dst=".bak" || [[ -n "$drt" ]] && echo invalid flag && exit
+[[ -n "$drt" ]] && [[ "$drt" == "-r" ]] && src=".xzm" && dst=".bak" || { [[ -n "$drt" ]] && echo invalid flag && exit ; }
 r=$(ls -1 | grep ".*${1}.*${src}" | grep -v "$dst" | wc -l)
 if [ "$r" -gt 0 ]; then
     for mods in ${PWD}"/"*$1*$src; do [[ "$1" == "_uid_" ]] && [[ "$mods" == *"_uid_L"* ]] && continue ; fname=${mods%"$src"}$dst ; test -e $fname && { red Filename conflict $fname already exists. ; test -e $omf && rm $omf; exit 0; } ; echo $mods ; done >> $oMF
@@ -261,15 +247,12 @@ for mods in $PWD"/"*_uid_*.xzm; do
     dest="/mnt/loop-$(basename "$mods" .xzm)"
     mkdir $dest
     if mountpoint -q $dest; then echo "Error: $dest already mounted. Everything preserved."; exit 1; fi
-   	if [ ! -f "$mods" ]; then echo "Error: In wrong directory. '$mods' not found."; exit 1; fi
-    mount -o loop $mods $dest
-   	find "${dest}/" -type f -name '.wh.*' -printf '%P\0' | while IFS= read -r -d '' file; do
-        k=$( echo "$file" | sed -e 's/^\.wh\.//')   # grabs the filename from the path strip the .wh. from start our file or directory name  -e 's@.*/@@' 
-    #       p=$(echo "$k" | sed 's/^\.wh\.//')  # strip the .wh. from start our file or directory name
-    #       p=$( echo "$file" | sed -E 's|(.*\/)\.wh\.|\1|') # same thing but with path in it 
-    #       x=$( stat -c '%Y' "$file") # get modified date of .wh. file
+	if [ ! -f "$mods" ]; then echo "Error: In wrong directory. '$mods' not found."; exit 1; fi
+	mount -o loop $mods $dest
+	find "${dest}/" -type f -name '.wh.*' -printf '%P\0' | while IFS= read -r -d '' file; do
+        k=$( echo "$file" | sed -e 's/^\.wh\.//')
+    #       p=$( echo "$file" | sed -E 's|(.*\/)\.wh\.|\1|') # keep path remove .wh.
         test -e "$k" && rm -rf "$k";
-		
         test -e "$INAME"/*/"$k" || test -e "$file" && rm -f "$file"  #  { echo "y" | fixsqh >> $EXCL; echo "$y" >> $EXFILES; test -e "$y" && rm -f "$y"; }
     done
     unset IFS
@@ -279,10 +262,7 @@ for mods in $PWD"/"*_uid_*.xzm; do
             red "Error processing one of the modules ${mods}"
             cyan "Everything preserved. Check the script and try again. check /tmp/error.log"
             umount $dest
-            rm -rf $dest
-            rm $oMF
-            rm -rf $1
-            exit 1
+            rm -rf $dest ; rm $oMF ; rm -rf $1 ; exit 1
         else
             cyan "White out file detected and processed"  >&2
         fi
