Add files via upload

diff --git a/Nemesis/opt/recentchanges/recentchanges b/Nemesis/opt/recentchanges/recentchanges
--- a/Nemesis/opt/recentchanges/recentchanges
+++ b/Nemesis/opt/recentchanges/recentchanges
@@ -1,5 +1,5 @@
 #!/bin/bash
-#   NMS5                                                                            07/05/2026  v5.0
+#   NMS                                                                            07/24/2026  v6.5
 # entry point for recentchanges.
 #
 #   recentchanges. aka Developer buddy      recentchanges / recentchanges search
@@ -39,8 +39,8 @@ get_colors
 # CHANGEABLE
 
 
-export backend="database" 	# default   bash 2 gpg and queries text based stable tested  
-											# database   binary database faster queries 1 gpg and python (easier ha)
+export backend="database"     # default   bash 2 gpg and queries text based stable tested  
+                                            # database   binary database faster queries 1 gpg and python (easier ha)
 
 export email="john.doe@email.com" # default for asymmetrical gpg auth for STATPST
                                                         # asks for paraphrase and caches for 15 minutes
@@ -62,13 +62,12 @@ cmode="gzip"                   # default nothing. uses gzip compression level ba
                                            # xz        best compression
                                            # zstd     faster bootup
                                             # lzo      faster bootup
-archivesrh=5						# How many old searches to save and rnt.xzm in /tmp(all filtered files) pulled. These can be grabbed by recentchanges search and recentchanges 
-#
+archivesrh=5                    # How many old searches to save and rnt.xzm in /tmp(all filtered files) pulled. These can be grabbed by recentchanges search and recentchanges
+
 #SRC options
-#this script
 xzmname="Application$$" # What to name .xzm when using SRC and create the .xzm automatically without selecting or entering a name. mutually depedent on autooutput
 autooutput="false"
-#
+# end SRC options
 # end this script
 
 export tmpSRHS=7 # Default 7. for ANALYTICS. store most recent searches in /tmp try 30 and then run recentchanges query with STATPST false
@@ -78,7 +77,7 @@ export tmpSRHS=7 # Default 7. for ANALYTICS. store most recent searches in /tmp 
 
 
 export mMODE="mc"  # default. regular search
-								   		# mc      turbo mode run the search in parallel or multiple cores.
+                                           # mc      turbo mode run the search in parallel or multiple cores.
 
 
 export ANALYTICS="false" # store recent searches in /tmp       default false
@@ -98,12 +97,13 @@ export STATPST="true" # persistent storage searches encrypted in /usr/local/save
                                     # Only overhead is gpg compression set compression to off. At large size speeds can increase by as much as 50%.
                                     # if you prefer security turn ANALYTICS false and use this
 
-export xRC="false"	# false - default. run inotifywait to look for new files in /changes.
-									# if automation fails it doesnt effect the results as the purpose to to make file_creation_log and cache files over 1MB for ctimecache.gpg
-									# With this setting If true can reduce process overhead as larger created files or downloads the results are already there
+export xRC="false"    # false - default. run inotifywait to look for new files in /changes.
+                                    # if automation fails it doesnt effect the results as the purpose to to make file_creation_log and cache files over 1MB for ctimecache.gpg
+                                    # With this setting If true can reduce process overhead as larger created files or downloads the results are already there
 export _time=3600   # default xRC searches for 1 hour before closing. default is to clear file_creation_log
-export min_span=3600	# set above _time to increase capacity. 0 would leave the log untouched
-#Display
+export min_span=3600    # set above _time to increase capacity. 0 would leave the log untouched
+
+#Analytics
 export ANALYTICSECT="true" # provides more feedback
                                             # total search time ect
                                             # we dont want too much output on the terminal just a slight bit more
@@ -111,25 +111,38 @@ export ANALYTICSECT="true" # provides more feedback
 
 export FEEDBACK="true"  # include find output in terminal as well ie scrolling terminal look
 
-
+#Display
 export dspEDITOR="xed" # false.  default dont display text editor. launch text editor?
-										# featherpad
-										# xed  
+                                        # featherpad
+                                        # xed  
 
+# optional theme packages are supported for query. precedence is ttkbootstrap, sv-ttk then ttkazure or forest
+
+export BOOTSTRAPTHEME="darkly"  # default theme to use for ttkbootstrap
+
+export defaultTHEME="dark"  # dark - default for sv azure ect
+                                             # light
 
 ## Diagnostics
-export checkSUM="true"	# compare file checksums for slight changes
-										# slower useful if you want to check deeper level of stats
-export cdiag="true"       # add extra detail like filesize in output and critical events. Also check for hash collisions.
+# slower useful if you want to check deeper level of stats
+export checkSUM="true"    # compare file checksums for slight changes
+                                        # slower useful if you want to check deeper level of stats
+export checkMETHOD="md5sum"  # md5sum
+                                                # md5ent - include entropy
+                                                # b2sum - blake2 256 (note hash collision checks will be turned off)
+                                                # b2ent - include entropy - blake2 256 (note hash collision checks will be turned off)
+
+export cdiag="true"       #  check for hash collisions
 export supbrwr="true"   # supress cache warnings on terminal from known browsers? Mozilla... ect list top of rntfuncions see rntchangesfunctions
 export suppress="false"  # ..      all cdiag output to terminal except critical events
+
 
 export POSTOP="false" # Diagnostics. Create file doctrine. Runs post search operation that can only be done at this time as search is relevant
                                     # more overhead so recommend off unless one off. output /Downloads
                                     #
                                     # if it is run again and a file is still there it will not run the POSTOP and the script will set POSTOP to false to itself
 
-export proteusSHIELD="false"	# take initial hash of base modules 001-core.. ect database mode
+export proteusSHIELD="false"    # take initial hash of base modules 001-core.. ect database mode
 ## End Diagnostics
 
 export MODULENAME="rntfiles"    # prefix for search result file
@@ -142,6 +155,7 @@ export flth="/usr/local/save-changesnew/flth.csv"
 # END CHANGEABLE
 [[ "$mMODE" != "default" ]] && [[ "$mMODE" != "mc" ]] && echo incorrect mMODE && exit 
 [[ "$STATPST" == "true" ]] && [[ "$ANALYTICS" == "true" ]] && { echo With STATPST cant run with ANALYTICS. for security reasons as its stored in gpg. ; } && exit
+[[ "$STATPST" = "false" ]] && [[ "$ANALYTICS" = "false" ]] && { echo STATPST or ANALYTICS not set select in recentchanges ; exit ; }
 [[ "$STATPST" == "false" ]] && [[ "$backend" == "database" ]] && echo database requires STATPST && exit
 if [ "$1" = "-v" ]; then get_vrn $1 ; elif [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ] || [ "$1" = "-help" ]; then get_vrn $1; fi
 
@@ -151,6 +165,8 @@ if (( EUID != 0 )); then
     exec sudo /opt/recentchanges/recentchanges "$1" "$2" "$3" "$(id -un)" "$PWD"
     exit
 fi
+is_sum="false"  # ensure the right hash program is used set in get_hashmethod
+get_hashmethod "$0"
 
 argone=${1:-noarguser}
 argtwo=${2:-noarguser}
@@ -169,9 +185,8 @@ fi
 
 USR="$4"
 passdir="$5"
-
-if  ! id $USR>/dev/null 2>&1; then echo "user: $USR not found"; exit 1; fi
 if [ "$4" == "" ] || [ "$5" == "" ]; then USR="guest" ; passdir=$PWD ; fi #Default user
+if  ! id $USR>/dev/null 2>&1; then echo "user: $USR not found"; exit 1; fi
 if [ "$3" == "SRC" ]; then echo "Incorrect usage please use recentchanges SRC s , s SRC or SRC" && exit 1; fi
 if [ -z "$argf" ]; then argf="bnk"; fi #Default
 
@@ -179,22 +194,21 @@ export DISPLAY=:0  # for tkl and root xed featherpad
 export XAUTHORITY=/home/$USR/.Xauthority
 
 if [ "$1" == "reset" ]; then
-	if [ "$STATPST" == "true" ]; then
-		 python3 /usr/local/save-changesnew/pstsrg.py "$0" "$pydbpst" "root" $email $mMODE $compLVL $checkSUM "true" "$logpst" "$statpst" "$ctimecache"
-		ret=$?
-		[[ $ret -eq 0 ]] && { remove_gpg ; exit 0 ; }
-		exit 1
-	else
-		echo "reset requries STATPST for default or database key reset" && exit 1
-	fi
+    if [ "$STATPST" == "true" ]; then
+         python3 /usr/local/save-changesnew/pstsrg.py "$0" "$pydbpst" "root" $email $mMODE $compLVL $checkSUM $checkMETHOD "true" "$logpst" "$statpst" "$ctimecache"
+        ret=$?
+        [[ $ret -eq 0 ]] && { remove_gpg ; exit 0 ; }
+        exit 1
+    else
+        echo "reset requries STATPST for default or database key reset" && exit 1
+    fi
 elif [ "$1" == "query" ]; then
-	if [ "$backend" == "default" ]; then
-		[[ -z $2 ]] && THETIME="noarguser" || THETIME=$2
+    if [ "$backend" == "default" ]; then
+        [[ -z $2 ]] && THETIME="noarguser" || THETIME=$2
         /usr/local/save-changesnew/query $THETIME $USR "$passdir"
         exit
     else
-
-        python3 /usr/local/save-changesnew/query.py "$0" $pydbpst $USR $email $mMODE $compLVL $checkSUM
+        python3 /usr/local/save-changesnew/query.py "$0" $pydbpst $USR $email $mMODE $compLVL $checkSUM $checkMETHOD $BOOTSTRAPTHEME $defaultTHEME
         exit
     fi
 fi
@@ -221,12 +235,18 @@ SORTCOMPLETE=$tmp/list_complete_sorted.txt			;	LCLMODULENAME=${chxzm:1:8}
 RECENTNUL=$tmp/list_recentchanges_filterednul.txt	;	USRDIR=/home/$USR/Downloads
 SVFOLDERS=$tmp/save.rncfoldersmanifest.tmp			;	SVFILES=$tmp/save.rncfilesmanifest.tmp
 
-cdir=/tmp/dbctimecache/											;	secondary=()
-cerr=/tmp/cerr															;	arrreject=()
-slog=/tmp/scr															;	arrfiles=()
+cdir=/tmp/dbctimecache/											;	cerr=/tmp/cerr
+datadict="${cdir}datadict"										;	slog=/tmp/scr
+secondary=()															;	arrreject=()
+arrfiles=()
+
+declare -A created
 
 CACHE_F="${cdir}ctimecache"
 INOTIFY_CACHE="${cdir}inotify_cache"
+INOTIFY_PID_FILE=/tmp/inotify_watcher.pid
+INOTIFY_DEBUG_FILE=/tmp/inotify.log
+
 LOCKFILE=/tmp/pblk.lock
 BRAND=$(date +"MDY_%m-%d-%y-TIME_%R" | tr ':' '_')
 FLBRAND=$(date +"MDY_%m-%d-%y-TIME_%R_%S" | tr ':' '_')
@@ -260,6 +280,7 @@ flsrh="false"
 # /etc /home /lib /lib64 /opt /root /sbin /tmp /usr /var
 F=( / )
 TAIL=(-not -type d -printf '%T@ %A@ %C@ %i %M %n %s %u %g %m %p|%l\0')
+PRUNE=("(" "-path" "$datadict" "-prune" ")" "-o")
 
 mkdir $tmp
 mkdir $tmp$workdir
@@ -276,7 +297,11 @@ else
     THETIME="$argone"
     start=$(date +%s.%N)
     [ "$THETIME" == "SRC" ] &&{ SRCDIR=$THETIME; THETIME="$argtwo"; }  # shift
-    [ "$2" == "SRC" ] && SRCDIR=$2 || { [ "$2" == "SEARCH" ] || [ "$2" == "search" ]; } && echo "The SRC tag is for recentchanges only" && exit
+    if [ "$2" == "SRC" ]; then
+        SRCDIR=$2
+    elif [ "$2" == "SEARCH" ] || [ "$2" == "search" ]; then
+        echo "Exiting not a search" && exit
+    fi
 
 fi
 
@@ -286,22 +311,22 @@ if [ "$argf" == "filtered" ]; then
 fi
 
 if [ "$THETIME" != "noarguser" ]; then
-	if [ "$THETIME" -ge 0 ] 2>/dev/null; then
+    if [ "$THETIME" -ge 0 ] 2>/dev/null; then
         argone=$THETIME
         search_time=$argone
         search_string="files $2 seconds old or newer"
-		comp $argone
-		tmn=$qtn
+        comp $argone
+        tmn=$qtn
 
     else
         argone=".txt"
-    	test -d "$passdir" || { echo "Invalid argument $passdir . PWD required."; exit 1; }
-		cd "$passdir"  || exit
-    	filename="$argtwo"
-    	test -f "$filename" || { test -d "$filename" || echo no such directory file or integer; exit 1; }
-    	parseflnm="${argtwo##*/}"
-		if [ "$parseflnm" == "" ]; then parseflnm="$(echo "$argtwo" | sed -e 's/\/$//' -e 's@.*/@@')" ; fi
-    	cyan "searching for files newer than $filename "
+        test -d "$passdir" || { echo "Invalid argument $passdir . PWD required."; exit 1; }
+        cd "$passdir"  || exit
+        filename="$argtwo"
+        test -f "$filename" || { test -d "$filename" || echo no such directory file or integer; exit 1; }
+        parseflnm="${argtwo##*/}"
+        if [ "$parseflnm" == "" ]; then parseflnm="$(echo "$argtwo" | sed -e 's/\/$//' -e 's@.*/@@')" ; fi
+        cyan "searching for files newer than $filename "
 
         if [ "$filtered" == "true" ]; then
             filtered="false"
@@ -310,37 +335,41 @@ if [ "$THETIME" != "noarguser" ]; then
             astring=" filtered"
             filtered="true"
         fi
-		file_path="$passdir/$parseflnm"
+        file_path="$passdir/$parseflnm"
         flsrh="true"
-		ct=$(date +%s)
-		fmt=$(stat -c %Y "$filename")
-		ag=$(( ct - fmt ))
-		search_time=$ag
-		search_string="files newer than $filename"
-		deltadiff=$( timedelta $STRTTIME $ag 6)
-		comp $ag
-		ag=$qtn
-		MMIN=(-newer "$filename")
-		CMIN=(-cmin "-$ag")
+        ct=$(date +%s)
+        fmt=$(stat -c %Y "$filename")
+        ag=$(( ct - fmt ))
+        search_time=$ag
+        search_string="files newer than $filename"
+        deltadiff=$( timedelta $STRTTIME $ag 6)
+        comp $ag
+        ag=$qtn
+        MMIN=(-newer "$filename")
+        CMIN=(-cmin "-$ag")
     fi
 else
     search_string="files 5 minutes old or newer"
     argone="5" ; tmn=$argone ; search_time=300
 fi
+
+cyan "searching for$astring $search_string"
+
 if [ "$tmn" != "" ]; then
-	MMIN=(-mmin "-$tmn")
-	CMIN=(-cmin "-$tmn")
+    MMIN=(-mmin "-$tmn")
+    CMIN=(-cmin "-$tmn")
 fi
 findrelavant
 findfiles
 
 if [ -s $SORTCOMPLETE ]; then
 
-	syschg="true"
+    syschg="true"
 
-	sort -u -o  $SORTCOMPLETE $SORTCOMPLETE 
+    sort -u -o  $SORTCOMPLETE $SORTCOMPLETE 
 
-	inclusions $SORTCOMPLETE
+    cp $SORTCOMPLETE /home/guest/tpp
+    inclusions $SORTCOMPLETE
 
     if [ "$flsrh" != "true" ]; then
         s=${STRTTIME%%.*}
@@ -349,15 +378,15 @@ if [ -s $SORTCOMPLETE ]; then
         awk -v tme="$PRD" '{ ts = $1 " " $2; if (ts <= tme) print }' $SORTCOMPLETE > $tout ; mv $tout $SORTCOMPLETE
     fi
 
-	sort -u -o $SORTCOMPLETE $SORTCOMPLETE
+    sort -u -o $SORTCOMPLETE $SORTCOMPLETE
 
-	process_sort $SORTCOMPLETE $TMPOPT
+    process_sort $SORTCOMPLETE $TMPOPT
 
     cat $TMPOPT | grep ' /tmp/' > $TMPOUTPUT
     sort -o $TMPOUTPUT $TMPOUTPUT
-	sed -i '/\"\/tmp/d' $SORTCOMPLETE
-	sed -i '/ \/tmp/d' $TMPOPT
-	sort -o $TMPOPT $TMPOPT
+    sed -i '/\"\/tmp/d' $SORTCOMPLETE
+    sed -i '/ \/tmp/d' $TMPOPT
+    sort -o $TMPOPT $TMPOPT
 
     cp $TMPOPT $RECENT
 
@@ -377,15 +406,15 @@ if [ -s $SORTCOMPLETE ]; then
     FLTOUT="/tmp"$MODULENAME"ItemsFilteredout"
 
     if [ "$flsrh" == "true" ]; then
-	    flnm="xNewerThan_$parseflnm"
-	    flnmdff="xDiffFromLast_$parseflnm"
+        flnm="xNewerThan_$parseflnm"
+        flnmdff="xDiffFromLast_$parseflnm"
 
     elif [ "$argf" == "filtered" ]; then
-	    flnm="xFltchanges_"$argone
-	    flnmdff="xFltDiffFromLastSearch_"$argone
+        flnm="xFltchanges_"$argone
+        flnmdff="xFltDiffFromLastSearch_"$argone
     else
-	    flnm="xSystemchanges"$argone
-	    flnmdff="xSystemDiffFromLastSearch"$argone
+        flnm="xSystemchanges"$argone
+        flnmdff="xSystemDiffFromLastSearch"$argone
     fi
 
     if [ "$search" == "false" ]; then
@@ -432,18 +461,21 @@ if [ -s $SORTCOMPLETE ]; then
 
     # prep OLDSORT
     # possible sort?
+
     # sed -i '/^[[:space:]]*$/d' $OLDSORTED  # remove blank lines
 
-    [[ -n $OLDSORTED ]] && nodiff="true" && comm -23 "$OLDSORTED" $logf > "$difffile"
+    # 07/24/2026
+    # added sort -u -o $OLDSORTED $OLDSORTED
+    [[ -n $OLDSORTED ]] && { sort -u -o $OLDSORTED $OLDSORTED ; nodiff="true" ; comm -23 "$OLDSORTED" $logf > "$difffile" ; }
 
     cp $logf "$dirSRC$MODULENAME$flnm"
     chown $USR "$dirSRC$MODULENAME$flnm"
 
     isdiff "$difffile" $TMPOPT $TMPCOMPLETE
 
-	backend $argf
-	filterhits $TMPOPT $flth
-	postop $SORTCOMPLETE $0
+    backend $argf
+    filterhits $TMPOPT $flth
+    postop $SORTCOMPLETE $0
     test -e "$difffile" && chown $USR "$difffile"
 
 fi
@@ -454,8 +486,8 @@ if [ "$ANALYTICS" == "true" ] && [ "$STATPST" == "false" ]; then
     if [ ! -f /tmp/rc/full ]; then cyan "Search saved in /tmp"; fi
 fi
 
-test -d "$tmp" && rm -rf "${tmp:?}" 
-test -d "$atmp" && rm -rf "${atmp:?}"
+test -d "$tmp" && rm -rf "$tmp"
+test -d "$atmp" && rm -rf "$atmp"
 
 logic "Refer to /rntfiles_MDY folder for the previous search"
 analytics
