Add files via upload

diff --git a/Porteus/usr/local/save-changesnew/clearcache b/Porteus/usr/local/save-changesnew/clearcache
--- a/Porteus/usr/local/save-changesnew/clearcache
+++ b/Porteus/usr/local/save-changesnew/clearcache
@@ -1,15 +1,18 @@
 #!/bin/bash
-# Clear cache from gpgs                 06/10/2026 
+# Clear cache from gpgs                 07/22/2026
 # usage. None required. $1 username if one isnt provided default is used `guest`. $2 means from database reset literal exit early
+CONFIG_FILE="/opt/porteus-scripts/recentchanges"
+SCRIPT_PATH="/usr/local/save-changesnew"
 . /usr/share/porteus/porteus-functions
 get_colors
-. /usr/local/save-changesnew/save-changesnewfnts
-. /usr/local/save-changesnew/rntchangesfunctions
+. "$SCRIPT_PATH"/save-changesnewfnts
+. "$SCRIPT_PATH"/rntchangesfunctions
 if [[ $(whoami) != "root" ]]; then su - -c "/usr/local/save-changesnew/clearcache `whoami`" ; exit ; fi 
 USR="$1"
 [[ -z "$USR" ]] && USR="guest"
 
 
+# patterns to delete from db on cache clear. 
 # deletes from logs. ANALYTICS  deletes frm logs. STATPST  logs and stats
 patterns=(
     'caches'
@@ -17,14 +20,14 @@ patterns=(
     'Cache2'
     '\.cache'
     'share/Trash'
-	"/home/$USR/Downloads/rntfiles"
-	"/home/$USR/\.local/state/wireplumber"
+    "/home/$USR/Downloads/rntfiles"
+    "/home/$USR/\.local/state/wireplumber"
     '/usr/share/mime/application'
     '/usr/share/mime/text'
     '/usr/share/mime/image'
-	'release/cache'
+    'release/cache'
     '\.local/share'
-    '/usr/local/save-changesnew/flth\.csv'
+    "$SCRIPT_PATH/flth\.csv"
 ) 
 
 
@@ -32,7 +35,7 @@ patterns=(
 # anything after "sed -i '/ and before /d'
 clear_flth() {
 literal=()
-literal+=("\/home\/'\"\${2}\"'\/Downloads\/rntfiles") 
+literal+=("\/home\/'\"\${2}\"'\/Downloads\/rntfiles")
 literal+=("\.cache")
 literal+=("\/home\/'\"\${2}\"'\/\.config")
 literal+=("\.local\/share")
@@ -40,43 +43,39 @@ literal+=("\/var\/cache")
 # literal+=("\.bash_history")
 
 for pat in "${literal[@]}"; do
-	y=$( grep -F "sed -i '/$pat/d" $flth | cut -d',' -f2)
+    y=$( grep -F "sed -i '/$pat/d" $flth | cut -d',' -f2)
 
-	if [ -n "$y" ] && (( y > 0 )); then
-		is_diff="true"
-		lno=$(grep -Fn "sed -i '/$pat/d'" "$flth" | cut -d: -f1)
-		if [[ -n $lno ]]; then
-			sed -i "${lno}s/,[0-9]\+\$/,0/" $flth
-		fi
-	fi
+    if [ -n "$y" ] && (( y > 0 )); then
+        is_diff="true"
+        lno=$(grep -Fn "sed -i '/$pat/d'" "$flth" | cut -d: -f1)
+        if [[ -n $lno ]]; then
+            sed -i "${lno}s/,[0-9]\+\$/,0/" $flth
+        fi
+    fi
 done
 }
-
 
 # declare -p patterns . prints the array  # echo "sed -i \"\|$pat|d\" \"$1\"  debug output
 clear_c() { for pat in "${patterns[@]}"; do sed -i "\|$pat|d" $1 ; done ; }
 ctmp() { if [ -d /tmp/rc ]; then for file in /tmp/rc/*; do [[ -s $file ]] && clear_c $file ; done ; fi ; }
 decrypt(){	if ! gpg --yes -d -o $1 $2; then red "Failed to decrypt  ${2}" && rm $atmp && exit 1; fi; }
 encr() { if ! gpg --yes -e -r $mail -o $2 $1; then red "Rencryption failed. Everything preserved" && rm $atmp && exit 1; fi; }
-atmp=/tmp/atmp$$									;	logpst="/usr/local/save-changesnew/logs.gpg"
-efile="/opt/porteus-scripts/recentchanges"	;	statpst="/usr/local/save-changesnew/stats.gpg"
-email="john.doe@email.com"					;	pydbpst="/usr/local/save-changesnew/recent.gpg"
-flth="/usr/local/save-changesnew/flth.csv"	;	xdata=$atmp/logs_stats.log
+atmp=/tmp/atmp$$    ;   flth="$SCRIPT_PATH"/flth.csv
+xdata=$atmp/logs_stats.log
+
 is_diff="false"
-rlt=$(sed -n 's/.*export logpst=\([^ ]*\).*/\1/p' "$efile")
-rltt=$(sed -n 's/.*export statpst=\([^ ]*\).*/\1/p' "$efile")
-mail=$(sed -n 's/.*export email=\([^ ]*\).*/\1/p' "$efile")
-rlt=${rlt//\"/} ; rltt=${rltt//\"/} ; mail=${mail//\"/}
-[ -z "$rlt" ] && rlt="$logpst" ; [ -z "$rltt" ] && rltt="$statpst" ; [ -z "$mail" ] && mail=$email
+
+get_inclusion "$CONFIG_FILE"
 
 mkdir $atmp 
 [[ -n "$2" ]] && { clear_flth && [[ "$is_diff" = "true" ]] && echo "Filter hits cleared."; exit 0; }
-et=$(sed -n 's/.*export ANALYTICS=\([^ ]*\).*/\1/p' $efile) ; et=${et//\"/}
-if [[ "$et" == "true" ]]; then echo "Clearing tmp searches" && ctmp ; clear_flth ; exit ; fi
+analytics=$(sed -n 's/.*export ANALYTICS=\([^ ]*\).*/\1/p' $CONFIG_FILE) ; analytics=${analytics//\"/}
+if [[ "$analytics" == "true" ]]; then echo "Clearing tmp searches" && ctmp ; clear_flth ; exit ; fi
 
-test -f $rlt || { cyan "logpst not found." && exit; } ; test -f $rltt || { cyan "statpst not found." && exit; }
-# lggpg=$( echo $rlt | fixcmp | fixOT) ; sttgpg=$( echo $rltt | fixcmp | fixOT) ; dbgpg=$( echo $rlttt | fixcmp | fixOT)
-decrypt $xdata $rlt ; clear_c $xdata ; encr $xdata $rlt && rm $xdata
-decrypt $xdata $rltt ; clear_c $xdata ; sed -i '/^$/d' $xdata ; encr $xdata $rltt && rm $xdata
+test -f $log || { cyan "logpst not found." && exit; } ; test -f $stat || { cyan "$statpst not found." && exit; }
+# lggpg=$( echo $log | fixcmp | fixOT) ; sttgpg=$( echo $stat | fixcmp | fixOT) ; dbgpg=$( echo $db | fixcmp | fixOT)
+decrypt $xdata $log ; clear_c $xdata ; encr $xdata $log && rm $xdata
+decrypt $xdata $stat ; clear_c $xdata ; sed -i '/^$/d' $xdata ; encr $xdata $stat && rm $xdata
 clear_flth
 rm -rf $atmp && green "Cache succesfully cleared"
+
diff --git a/Porteus/usr/local/save-changesnew/inotify b/Porteus/usr/local/save-changesnew/inotify
--- a/Porteus/usr/local/save-changesnew/inotify
+++ b/Porteus/usr/local/save-changesnew/inotify
@@ -1,21 +1,28 @@
 #!/usr/bin/env bash
-#inotify db5                     07/05/2026
-# inotify to watching either / or /mnt/live/memory/changes. filters out some files and also browser suppressions in sbwr array. see rntchangesfunctions
-# Also filters out app inclusions in inotifyexl array
+#inotify db6.5                     07/20/2026
+# inotify to watching either / or /mnt/live/memory/changes. filters out some files and also browser suppressions in sbwr array. this is part of general excludes see rntchangesfunctions.
+# Also filters out app inclusions in inotifyexl array in general excludes section
 # result of wanting to prepare hashed files that are downloads from a package manager or are copied files that have preserved
 # metadata where ctime is greater than mtime. This is because they would not show up in a regular file search.
 #
 # as progress was made with watchdog the implementation was changed to search for created files. Then instead of preparing a results file the
-# results file is used as an indirect feature as file_creation_log.txt can be viewed for created files. The second output is the cache which will 
+# results file is used as an indirect feature. The file_creation_log.txt that can be viewed for created files. The second output is the cache which will
 # save the hash for the main search. So if anything goes wrong with inotify the results are not effected.
 #
-# result created cache of created files over 1MB and also output to a created files log.
+# result created cache of created files over 1MB and also output to a created files log
+
 #SCRIPT_PATH="$( dirname "$0")"
 #. "$SCRIPT_PATH"/rntchangesfunctions
-. /usr/local/save-changesnew/rntchangesfunctions
+CONFIG_FILE="/opt/porteus-scripts/recentchanges"
+SCRIPT_PATH="/usr/local/save-changesnew"
+. "$SCRIPT_PATH"/rntchangesfunctions
 
 MOUNT_FOLDERS=("mnt" "media")
 MOUNTS_INCLUDE=("home")
+
+# general excludes regex
+# subtitutes
+#    "/tmp/${LCLMODULENAME}_MDY_[^/]*/${LCLMODULENAME}x.+$"
 
 inotifyexl() {
 inclusion=(
@@ -23,46 +30,39 @@ inclusion=(
     ".*/Downloads/${LCLMODULENAME}x"
     "/tmp/${LCLMODULENAME}x"
     "/tmp/rc/${LCLMODULENAME}_MDY"
-    "/tmp/${LCLMODULENAME}_MDY_[^/]*/${LCLMODULENAME}x.+$"
     "/usr/local/save-changesnew/flth.csv"
     "/usr/local/save-changesnew/logs.gpg"
     "/usr/local/save-changesnew/recent.gpg"
     "/usr/local/save-changesnew/stats.gpg"
     "/usr/local/save-changesnew/ctimecache.gpg"
+    "\.local/share/recently-used.xbel"
     "$output_file"
-	"$cache_file"
+    "$cache_file"
     "$CACHE_F"
 )
 }
+# end general excludes regex
+
 
 MAX_JOBS=8
 IDLE=$(( MAX_JOBS / 2 ))
 BRAND=`date +"MDY_%m-%d-%y-TIME_%R"|tr ':' '_'`
 
 ch="/mnt/live/memory/changes"
-fmt="%Y-%m-%d %H:%M:%S"
-
-# These can be user set so get fromm recentchanges script. and default fallbacks in case cant find
-efile="/opt/porteus-scripts/recentchanges"
-logpst="/usr/local/save-changesnew/logs.gpg"				;    statpst="/usr/local/save-changesnew/stats.gpg"
-pydbpst="/usr/local/save-changesnew/recent.gpg"			;    ctimecache="/usr/local/save-changesnew/ctimecache.gpg"  # search cache
-email="john.doe@email.com"
-rlt=""
-rltt=""
-rlttt=""
-mail=""
 
 output_file=$1  # main output
 LCLMODULENAME="$2"
 cache_file="$3"  # main script cache on decrypt for exclude
 CACHE_F="$4"  # secondary output cache
-CSZE="$5"
-cdir="$6"
-LOCKFILE="$7"
-checkSUM="$8"
-time=$9
-min_span="${10}"  # set greater than time to increase capacity. 0 prevents log from being cleared. otherwise increase _time in /opt/porteus-scripts/recentchanges
-debug_file="${11}"  # debug output of this script
+inotify_pid_file="$5"
+debug_file="$6"  # debug output of this script
+cdir="$7"
+datadict="$8"
+LOCKFILE="$9"
+CSZE="${10}"
+checkMETHOD="${11}"
+time="${12}"
+min_span="${13}"  # set greater than time to increase capacity. 0 prevents log from being cleared. otherwise increase _time in /opt/porteus-scripts/recentchanges
 
 match_found=0
 
@@ -70,7 +70,6 @@ debug_log="false"  # add debug
 
 pblk_log_file=/tmp/output  # debug output of pblk
 
-dpaths=()
 declare -A mvfrm_pending
 declare -A create_pending
 
@@ -82,9 +81,10 @@ j=${sleep_times[sleep_index]}
 prev_size=-1
 incr=0
 
-STRTTIME=$(date +%s)
+is_sum="false"  # ensure the right hash program is used and is set in get_hashmethod
+get_hashmethod "inotify"
 
-get_inclusion "$efile"
+STRTTIME=$(date +%s)
 
 :> $CACHE_F ; :> $pblk_log_file
 
@@ -95,47 +95,57 @@ echo "$BRAND inotify started" >> $debug_file
 pst=$PWD
 ch="${ch%/}"
 [[ -d $ch ]] && { cd $ch && abpath="$ch/" || exit ; } || { [[ ! -d $ch ]] && cd "/" && abpath="/" || exit ; }
-cd $pst || exit
+cd "$pst" || exit
 
 sbwr
 inotifyexl
-inclusion+=("$rlt" "$rltt" "$rlttt" "/usr/local/save-changesnew/ctimecache.gpg")
+get_inclusion $CONFIG_FILE
+inclusion+=("$log" "$stat" "$db" "$cache")
 
-exec 200>"$LOCKFILE"
+# exec 200>"$LOCKFILE"
+mkdir -p $datadict || exit ; chmod 700 $datadict
 
-exclude="^(proc|sys|dev|run"
+#(
+#    while true; do
+#        sleep 900
+#        find $datadict -mindepth 1 -mmin +15 -delete
+#    done
+#) &
+#pid2=$!
+#trap 'kill "$pid2" 2>/dev/null' EXIT
+trap 'rm -rf -- "${datadict:?}"/* ; rm -f "$inotify_pid_file"' EXIT
+
+# specific exclusions
+exclude="$abpath(proc|sys|dev|run"
 for fld in "${MOUNT_FOLDERS[@]}"; do exclude+="|$fld" ; done
-exclude+="|^/tmp/${LCLMODULENAME}_MDY_.*-TIME_.*(/.*)?\$"  # created by main script
 exclude+=")"
+exclude+="|/tmp/${LCLMODULENAME}_MDY_.*-TIME_.*"  # created by main script
+exclude+="|$datadict"
+# end specific exclusions
+
 # search in / or changes
+# a CREATE event should match a MOVED_TO event but there can be cases where the CREATE event wasnt seen or lost so it logs
+# cookie pairs a moved from event to moved to event. src -> dest
 
 timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e moved_from --format '%e|%c|%w%f%0' $abpath | while read -r -d '' o; do
 
-    [[ "$debug_log" = "true" ]] && log_date=$(date +"$fmt")
-
+    key=""
     event=${o%%|*}
     o=${o#*|}
-    cookie=${o%%|*}  # pairs a moved from event to a moved to event. src -> dest
+    cookie=${o%%|*}  
     o=${o#*|}
 
-    if [[ $abpath != "/" ]]; then o="${o#$ch}" ; fi
+    if [[ $abpath != "/" ]]; then o=${o#"$ch"} ; fi
 
-    log_lineout $debug_log $debug_file "$log_date" "File event: $event file: $o"
+    log_lineout $debug_log $debug_file "File event: $event file: $o"
 
     if [[ -d "$o" ]]; then
-        log_lineout $debug_log $debug_file "$log_date" "Directory created: $o"
-        #incase the file is created at the same time ie scripts or a process and could be missed by intoify. however during testing -r captures it
-        #find "$o" -cmin -5 -not -type d -printf '%T@ %A@ %C@ %i %M %n %s %u %g %m %p\0' |
-        #while IFS= read -r -d '' record; do
-        #    if [[ "$o" =~ \.(tmp|swp|bak|part|crdownload|partial|lock)$ ]]; then continue ; fi  
-        #    echo "$log_date found new file in dir $o" >> /tmp/inotify.log
-        #    sblk "$record" "$output_file" "/dev/null" "$checkSUM" "$xMODE" "$CACHE_F"
-        #done
+        log_lineout $debug_log $debug_file "Directory created: $o"
         continue
 
     elif [[ -f "$o" ]]; then
 
-        log_lineout $debug_log $debug_file "$log_date" "inotify found checking for matches $o"
+        log_lineout $debug_log $debug_file "inotify found checking for matches $o"
 
         match_found=0
         for item in "${webb[@]}"; do
@@ -153,16 +163,24 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
             done
         fi
 
-        # a CREATE event should match a MOVED_TO event
-        # but there can be cases where the CREATE event wasnt seen or lost so it logs
         if [[ "$event" = "CREATE" ]]; then
-            create_pending[$o]=1
+            
+            read -r curr_size inode mod_time c_time < <(find "$o" -maxdepth 0 -printf '%s %i %T@ %C@\n' 2>/dev/null)
+            [[ -z "$c_time" ]] && continue
+
+            key="${inode}_${mod_time}"
+            create_pending[$o]=$key
+            printf '%s\n' "$o" > "$datadict/$key"
+
         elif [[ "$event" = "MOVED_FROM" ]]; then
-            mvfrm_pending["$cookie"]="$o"  # this is needed in the MOVED_TO event so can verify the src from the MOVED_FROM to a CREATE event. normal operation is verify dest as it would match in most cases from web browsers ect
+            mvfrm_pending["$cookie"]="$o"
             continue
         fi
 
         if [[ "$o" == *.* ]]; then
+            if [[ "$o" =~ \.org\.chromium\.Chromium ]]; then
+                continue
+            fi
             ext="${o##*.}"
             ext="${ext,,}"
             if [[ "$ext" =~ ^(tmp|temp|swp|bak|part|crdownload|partial|lock)$ ]]; then
@@ -171,19 +189,8 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
         fi
 
         if [[ "$event" = "MOVED_TO" ]]; then
-            src="${mvfrm_pending[$cookie]}"
-            if [[ -n "$src" ]]; then
-                unset 'mvfrm_pending[$cookie]'
-                if [[ -v create_pending[$src] ]]; then
-                    unset 'create_pending[$src]'
-                    log_lineout $debug_log $debug_file "$log_date" "inotify MOVED_TO unusual src was in create_pending on move after created file. src: $src dest or file: $o"
-                # normal
-                else
-                    pairhandle ; continue
-                fi
-            # normal
-            else
-                pairhandle ; continue
+            if phandle; then
+                continue
             fi
         fi
 
@@ -194,7 +201,7 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
             (
                 if [[ "$event" = "CREATE" ]]; then
                     if (( current_jobs > IDLE )); then
-                        log_lineout $debug_log $debug_file "$log_date" "system at has idle jobs: ($current_jobs) skipping stabilization wait $o"
+                        log_lineout $debug_log $debug_file "system at has idle jobs: ($current_jobs) skipping stabilization wait $o"
                     else
                         curr_size=0
                         prev_size=-1
@@ -202,32 +209,36 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
                         retried=0
                         sleep_index=0
 
-                        log_lineout $debug_log $debug_file "$log_date" "notify matched input to pblk waiting for stable size $o"
+                        log_lineout $debug_log $debug_file "notify matched input to pblk waiting for stable size $o"
 
                         stable=0
                         while :; do
                             (( incr++ ))
-                            curr_size=$(stat -c %s "$o" 2>/dev/null || echo -1)
-                            (( curr_size < 0 )) && break  # Nosuchfile
-                            if (( curr_size == prev_size )); then
+                            read -r curr_size inode < <( stat --format="%s %i" "$o" 2>/dev/null)
+                            [[ -z "$curr_size" ]] && curr_size=-1
+                            if (( curr_size < 0 )); then
+                                break
+                            elif (( curr_size == 0 )); then
+                                [[ $retried -ge $LIMIT ]] && stable=1 && break
+                                 j=${sleep_times[sleep_index]}
+                                 (( sleep_index < ${#sleep_times[@]} - 1 )) && (( sleep_index++ ))
                                 (( retried++ ))
-                                [[ $retried -ge $LIMIT ]] && stable=1 && break  # found
-                                sleep_index=0
+                            elif (( curr_size == prev_size )); then
+                                [[ $retried -ge $LIMIT ]] && stable=1 && break
                                 j=${sleep_times[0]}
+                                sleep_index=0
+                                (( retried++ ))
                             else
-                                retried=0
                                 (( sleep_index < ${#sleep_times[@]} - 1 )) && ((sleep_index++))
                                 j=${sleep_times[sleep_index]}
+                                retried=0
                             fi
                             prev_size="$curr_size" && sleep $j
                         done
-                        [[ "$debug_log" = "true" ]] && log_date=$(date +"$fmt")
-                        (( $curr_size )) || { log_lineout $debug_log $debug_file "$log_date" "inotify size stabilized looks like a download 0 bytes. returning for move event. file:$o" ; exit ; }
-
                         if (( stable == 1 )); then
-                            log_lineout $debug_log $debug_file "$log_date" "inotify size stabilized for pblk $o"
+                            (( curr_size )) && log_lineout $debug_log $debug_file "inotify size stabilized for pblk $o" || log_lineout $debug_log $debug_file "inotify size stabilized looks like a download 0 bytes. returning for move event. file:$o"
                         else
-                            log_lineout $debug_log $debug_file "$log_date" "inotify timed out waiting for stable size, proceeding anyway (checksum will self-guard): $o"
+                            log_lineout $debug_log $debug_file "inotify timed out waiting for stable size, proceeding anyway (checksum will self-guard): $o"
                         fi
                     fi
                 fi
@@ -236,7 +247,7 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
                 while IFS= read -r -d '' record; do
                     [[ -z "$record" ]] && continue
 
-                    pblk "$record" "$output_file" "/dev/null" $checkSUM $CSZE "$CACHE_F" "$cdir" $debug_log "$pblk_log_file"
+                    pblk "$record" "$output_file" "/dev/null" "$cdir" "$datadict" "$CACHE_F" $CSZE "$key" $event "$debug_log" "$pblk_log_file"
 
                 done
 
@@ -246,58 +257,23 @@ timeout "$time" inotifywait -m -r --exclude "$exclude" -e create -e moved_to -e 
             done
 
         else
-            log_lineout $debug_log $debug_file "$log_date" "inotify found excluded by matching skipped. for $o"
+            log_lineout $debug_log $debug_file "inotify found excluded by matching skipped. for $o"
         fi
      else
-        log_lineout $debug_log $debug_file "$log_date" "inotify file not found or parsing error. for $o"
+        log_lineout $debug_log $debug_file "inotify file not found or parsing error. for $o"
     fi
 done
 
-# original drafting
+# notes
 # stat --printf="%y %x %z %i %A %h %s %U %G %a %n" "$o"  # alternative doesnt print microsecond**
 # y 2026-01-14 00:48:20.527855839
 # have to parse with date -d "2026-01-14 00:48:20.527855839" +%s.%N 2>/dev/null
-
 #RS=$'\x1E'  # | sed "s/$/$RS/"  seperator   , then decode # file="${o//$RS/$'\n'}" 
-# { stat --format="%Y %X %Z %i %h %s %U %G %a %n" "$o" 2>/dev/null; printf '\0'; } | sblk /dev/stdin "$output_file" "/dev/null" $checkSUM $xMODE $CACHE_F  original appends \n before \0
-# { stat --printf="%Y %X %Z %i %h %s %U %G %a %n" "$o" 2>/dev/null ; printf '\0;' } | sblk /dev/stdin "$output_file" "/dev/null" $checkSUM $xMODE $CACHE_F
-#dpaths+=("/var") # downloads can be in 
-# collect some directories
-#while IFS= read -r d; do dpaths+=("$d") ; done < <(find /tmp -type d )
-#"${dpaths[@]}"
-
 # alternative,  limit scope to avoid max_user_watches limit
+# dpaths=()
 #while IFS= read -r d; do dpaths+=("$d") ; done < <(find /var -maxdepth 5 -type d ) #
-
-# find /var -maxdepth 1 -type l   find symlinks
-# find /mnt/live/memory/changes -type d | wc -l   count how many directories are in changes
-
 # downloads can be in /tmp , /var   /var/slapt-get    /var/cache    etc
 # if it is another distro we dont want changes **
-
-# notes
 # grep -r inotify /proc/*/fdinfo/* 2>/dev/null | wc -l  # current usage
 # cat /proc/sys/fs/inotify/max_user_watches  # watch limit
-
-# caching system to prevent possible extra work but not needed
-# mkdir -p $datadict || exit ; chmod 700 $datadict
-#(
-#    while true; do
-#        sleep 900
-#        find $datadict -mindepth 1 -mmin +15 -delete
-#    done
-#) &
-#pid2=$!
-#trap 'kill "$pid2" 2>/dev/null' EXIT
-#if [[ "$event" = "CREATE" ]]; then
-#    key="${fs}_${m_epoch}"
-#    if [[ -e "$datadict/$key" ]]; then
-#        log_lineout $debug_log $pblk_log_file "$log_date" "created event file was renamed or moved returned on: $1"
-#        return 1
-#	else
-#		log_lineout $debug_log $pblk_log_file "$log_date" "created event file key was $key on: $1"
-#    fi
-#fi
-#key="${a_sze}_${mtime}"
-#printf '%s\n' "$o" > "$datadict/$key"
 
diff --git a/Porteus/usr/local/save-changesnew/start_inotify b/Porteus/usr/local/save-changesnew/start_inotify
--- a/Porteus/usr/local/save-changesnew/start_inotify
+++ b/Porteus/usr/local/save-changesnew/start_inotify
@@ -1,44 +1,33 @@
 #!/usr/bin/env bash
-# supress output helper script to launch inotifywait optional logging   09/15/2025 07/05/2026
+# supress output helper script to launch inotifywait optional logging   09/15/2025 07/22/2026
 #nohup /usr/local/save-changesnew/inotify "$@" > /dev/null 2>&1 &
 # SCRIPT_PATH="$( dirname "$0")"
+. /usr/local/save-changesnew/inotifyfunctions
 fmt="%Y-%m-%d %H:%M:%S"
-debug_file=/tmp/inotify.log  # core inotify debug output
-echo $log_date > $debug_file
-if [ "$#" -lt 10 ]; then
-    echo "Usage: $0 log_file mdlnameprefix cache_file inotify_cache_file csze cdir lockfile checksum _time min_span" >&2
-	echo "not enough args" >> $debug_file
+inotify_pid_file="$5"
+inotify_debug_file="$6"  # core inotify debug output
+
+log_date=$(date +"$fmt")
+echo $log_date > "$inotify_debug_file"
+if [ "$#" -lt 13 ]; then
+    echo "Usage: $0 log_file mdlnameprefix cache_file inotify_cache_file inotify_pid_file inotify_debug_file cdir datadict lockfile csze checkmethod _time min_span" >&2
+    echo "not enough args" >> "$inotify_debug_file"
     exit 1
 fi
-log_date=$(date +"$fmt")
 
-setsid /usr/local/save-changesnew/inotify "$@" "$debug_file" >> "$debug_file" 2>&1 &  # nohup /usr/local/save-changesnew/inotify "$@" "$debug_file" >> $debug_file 2>&1 &
+if ! oldpid "$inotify_pid_file"; then
+    echo "failed to close a previously running process quiting" >> "$inotify_debug_file"
+    exit 1
+fi
+setsid /usr/local/save-changesnew/inotify "$@" >> "$inotify_debug_file" 2>&1 &  # nohup /usr/local/save-changesnew/inotify "$@" >> "$inotify_debug_file" 2>&1 &
 pid=$!
 sleep 1
 
 if ! kill -0 "$pid" 2>/dev/null; then
-    echo "inotify failed to start" >> $debug_file
+    echo "inotify failed to start" >> "$inotify_debug_file"
     exit 1
 fi
 
 # awk '{print $22}' /proc/5473/stat
-printf '%s|%s\n' "$pid" "$(ps -o lstart= -p "$pid")" > /tmp/inotify_watcher.pid
-
-oldpid() {
-local res=0
-if [[ -f $1 ]]; then
-    IFS='|' read -r stored_pid stored_start < $1
-    current="$(ps -o lstart= -p "$pid")"
-    if [[ -n "$current" ]]; then
-        if [ "$current_start" = "$stored_start" ]; then
-            if ! kill -- -$stored_pid; then
-                echo "failed to close old pid $stored_pid $stored_start"
-                res=1
-            fi
-        fi
-    fi
-    rm -f $1
-fi
-return $res
-}
+printf '%s|%s\n' "$pid" "$(ps -o lstart= -p "$pid")" > "$inotify_pid_file"
 
