Add files via upload

diff --git a/Porteus/usr/local/save-changesnew/recentchanges b/Porteus/usr/local/save-changesnew/recentchanges
--- a/Porteus/usr/local/save-changesnew/recentchanges
+++ b/Porteus/usr/local/save-changesnew/recentchanges
@@ -1,9 +1,11 @@
-#!/bin/bash
-#	rntfiles.xzm or -SRC application.xzm to /tmp																						11/19/2025
-. /usr/local/save-changesnew/rntchangesfunctions
-. /usr/local/save-changesnew/validprogram.sh
+#!/usr/bin/env bash
+#	rntfiles.xzm or -SRC application.xzm to /tmp																						01/09/2026
+SCRIPT_PATH="$( dirname "$0")"
+. "$SCRIPT_PATH"/rntchangesfunctions
+. "$SCRIPT_PATH"/validprogram.sh
 . /usr/share/porteus/porteus-functions
-get_colors                
+
+get_colors
 tmp=/tmp/tmp$$  															;	work=work$$
 workdir=/myfiles															;	chxzm=/rntfiles.xzm   
 TMPCOMPLETE=$tmp/tmp_complete.txt							;   TMPOPT=$tmp/tmp_holding
@@ -15,74 +17,82 @@ xdata2=/logs.log.log														;	RECENT=$tmp/list_recentchanges_filtered
 BRAND=$(date +"MDY_%m-%d-%y-TIME_%R" | tr ':' '_')	;	tout=$atmp/toutput.tmp
 FLBRAND=$(date +"MDY_%m-%d-%y-TIME_%R_%S" | tr ':' '_')
 
-validrlt="false"																;   validpdt="false"                                                  
-smsg="false"                                                                ;   autooutput="false"                                                                    
+validrlt="false"																;   validpdt="false"  # valid product
+# indicates a previous search
+smsg="false"                                                                ;   autooutput="false"
 goahead="true"
+
 
 tfile=$atmp$xdata
 tfile2=$atmp$xdata2
 
-xzmname="Application${$}"
 argone="$1"
 THETIME="$2"
 [[ "$3" = "SRC" ]] && SRCDIR="$3"
 USR="$4"
-ptmp="$5"
-fo="$6"
-[[ -s /tmp/"$6" ]] || { echo "recentchanges main list not found" && exit 3 ; }
-ft="$7"
-[[ -s /tmp/"$ft" ]] || { echo "recentchanges recent list not found" && exit 3 ; }
-fth="$8"
-[[ -s /tmp/"$fth" ]] || { echo "recentchanges null list not found" && exit 3 ; }
+xzmname="$5"
+ptmp="$6"
+
+
+# applicable files
+tmpopt_out="$7"  # filtered file list
+[[ -s /tmp/"$7" ]] || { echo "recentchanges main list not found" && exit 3 ; }
+sortcomplete_out="$8"  # SORTCOMPLETE for file times.
+[[ -s /tmp/"$8" ]] || { echo "recentchanges null list not found" && exit 3 ; }
+
 archivesrh=$9
 cmode=${10}  
 autooutput=${11}
+
 chown root:root -R $ptmp
 chmod 755 $ptmp
 mkdir $tmp
 mkdir $tmp$workdir
 mkdir $atmp
-mv "/tmp/$fo" $tmp/
-mv "/tmp/$ft" $tmp/
-mv "/tmp/$fth" $atmp/
-
-if ! grep -Eiq "artix|porteus" /etc/os-release; then goahead="false" ; fi
 
 
-awk '{$1=$2=""; sub(/^ +/, ""); print}' $TMPOPT > $RECENT # filepath
+# move each file away to new staging
+mv "/tmp/$tmpopt_out" $tmp/
+mv "/tmp/$sortcomplete_out" $tmp/
+# mv "/tmp/$tout_out" $atmp/
+#test -f "/tmp/$tout_out/" && rm "/tmp/$tout_out"
 
+if ! grep -Eiq "nemesis|porteus" /etc/os-release; then [[ ! -f /etc/porteus-version ]] && goahead="false" ; fi
+if grep -Eiq "artix" /etc/os-release; then [[ -d  /mnt/live/tmp ]] && goahead="true" ; fi
 
-# Copy files
-#> $tout
-#while IFS= read -r x; do  ; printf '%s\0' "$x"; done < $RECENT >> $tout
->$tfile
-while IFS= read -r -d '' x; do y="$( unescf "$x")" ; if cp -a --parents "$y" "$tmp$workdir" > /dev/null 2>> $tfile; then printf '%s %s\n' "$x" "success" >> $UPDATE; else echo "Failed to copy: $x" >&2; echo "ERROR: $x" >> $UPDATE; fi; done < $tout
-#cat $UPDATE
-unset IFS
-if [ -s $tfile ]; then echo >> $UPDATE ; fi
-test -e $tfile && rm $tfile
-echo $BRAND >> $UPDATE
-find $tmp$workdir -not -type d -print0 > $SVFILES
->$tout
-while IFS= read -r -d '' x; do x="$( escf "$x")"; echo "$x" ; done < $SVFILES >> $tout
-mv $tout $SVFILES
-sed -i -e "s|$tmp$workdir||g" $SVFILES
-cat $SVFILES | sed -e 's![^/]*$!!g' > $SVFOLDERS
+cut -d " " -f3- $TMPOPT > $RECENT  # filepaths from sorted list.
 
+:>$tfile
+
+if [ "$goahead" == "true" ]; then
+	# Copy files
+
+	while IFS= read -r x; do y="$( unescf "$x")" ; if cp -a --parents "$y" "$tmp$workdir" > /dev/null 2>> $tfile; then printf '%s \n' "$x success" >> $UPDATE; else echo "Failed to copy: $y" >&2; echo "ERROR: $x" >> $UPDATE; fi; done < $RECENT
+	unset IFS
+
+	if [ -s $tfile ]; then echo >> $UPDATE ; fi
+	test -e $tfile && rm $tfile
+	echo $BRAND >> $UPDATE
+	find $tmp$workdir -not -type d -print0 > $SVFILES
+	:> $tout
+	while IFS= read -r -d '' x; do x="$( escf "$x")"; echo "$x" ; done < $SVFILES >> $tout
+	mv $tout $SVFILES
+	sed -i -e "s|$tmp$workdir||g" $SVFILES
+	cat $SVFILES | sed -e 's![^/]*$!!g' > $SVFOLDERS
+fi
 # make .xzm from root folder
-if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then 
+if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
     arrfiles=()
-    arrreject=()
     appname=$xzmname
     FLTOUT="/tmp/${appname}ItemsFilteredout"
     test -e "/tmp/${appname}.xzm" && rm "/tmp/${appname}.xzm"
     rm "/tmp/"*"_xdata" 2> /dev/null
-    rlt=$( validprogram $SVFOLDERS)
+    rlt="$( validprogram $SVFOLDERS)"
  	if [ "$rlt" == "/" ]; then echo Fatal error. exiting. && exit 1 ; fi
     if [ "$rlt" != "" ]; then
         cat $SVFILES | grep "${rlt}" > $RECENTAPP ; cat $SVFILES | grep -v "${rlt}" > $RSYNCEXCL
-		find $tmp$workdir -type d -empty -delete 
-		while IFS= read -r p || [ -n "$p" ]; do  p="$( unescf "$p")" ; p="${p#/}" ; echo "$p" >> $tfile ; done < $RSYNCEXCL # This is for our SRC files after finding root
+		find $tmp$workdir -type d -empty -delete  # skip any file with new lines for exclude file
+		while IFS= read -r p || [ -n "$p" ]; do p="${p#/}" ; p="${p//\\\\n/$'\n'}" ; p="${p//\\ap5c/\\}" ; echo "$p" >> $tfile ; done < $RSYNCEXCL  # This is for our SRC files after finding root
         test -s $tfile && mksquashfs $tmp$workdir "/tmp/${appname}.xzm" -comp $cmode -ef $tfile || { [[ ! -s "$tfile" ]] && mksquashfs $tmp$workdir "/tmp/${appname}.xzm" -comp $cmode ; }
         cp $RECENTAPP "/tmp/${appname}_xdata" ; echo $BRAND >> "/tmp/${appname}_xdata"
         sort -o $RECENTAPP $RECENTAPP
@@ -92,15 +102,15 @@ if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
         cat $SORTCOMPLETE | grep -Fvf $RECENTAPP > $TMPCOMPLETE
 	    cd $tmp$workdir || exit
 	    srcpath="${rlt#?}"
-		> $tfile
+		:> $tfile
 		r=$( find "${rlt}" -type f | wc -l)  # system
 		s=$(grep -n 'MDY' "/tmp/${appname}_xdata" | head -n 1 | cut -d: -f1)
 		if [[ -n "$s" ]]; then s=$(( s - 1 )) ; else s=0 ; fi
 		x=0
-		y=$( wc -l < $RECENTAPP) # copied
-		while IFS= read -r -d '' f ; do echo "$f" >> $tfile ;  x=$(( x + 1 )) ; done < <(find "${srcpath}" \( -type f -o -type l \) -print0)  # Our system files is what we should be comparing		
+		y=$( wc -l < $RECENTAPP)  # copied
+		while IFS= read -r -d '' f ; do p="$( escf "$f")" ; printf '%s\n' "$p" >> $tfile ;  x=$(( x + 1 )) ; done < <(find "${srcpath}" \( -type f -o -type l \) -print0)  # Our system files is what we should be comparing
 		{ echo Root:"${rlt}" ; echo "File count: "$x "of ${y}" ; echo "System count: "$r ; echo ; echo ; } >> "/tmp/${appname}_xdata"   
-		if (( x < y )); then  #Default
+		if (( x < y )); then
 			sort -o $tfile $tfile
 			sort $RECENT > $tfile2
 			comm -23 $tfile $tfile2 > $tout
@@ -111,11 +121,16 @@ if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
 			{ echo "SRC mode failed. use recentchanges to package application." ; } >> "/tmp/${appname}_xdata"
 		fi
 		if (( r > s )); then echo "Status: Possibly missed base directory. Confirm files or use recentchanges for rntfiles.xzm." >> "/tmp/${appname}_xdata" ; fi
-        echo $BRAND >> $RECENTAPP
+
         if [ -s $TMPCOMPLETE ]; then { echo ; echo "Items filterout from filtered files."; echo ; cat $TMPCOMPLETE; }  >> "/tmp/${appname}_xdata" ; else echo "No items filtered out from filter."  >>"/tmp/${appname}_xdata" ; fi
-        find "$tmp$workdir$rlt" -type f -print0 > $TMPCOMPLETE
-        while IFS= read -r -d '' f; do  f="$( escf "$f")" ; arrfiles=("${arrfiles[@]}" "${f##*/}"); done < $TMPCOMPLETE
+        # original 
+        #find "$tmp$workdir$rlt" -type f -print0 > $TMPCOMPLETE
+        #while IFS= read -r -d '' f; do  f="$( escf "$f")" ; arrfiles=("${arrfiles[@]}" "${f##*/}"); done < $TMPCOMPLETE
+        while IFS= read -r f; do arrfiles=("${arrfiles[@]}" "${f##*/}"); done < $RECENTAPP  # save overhead by reading off $RECENTAPP for the names
+        echo $BRAND >> $RECENTAPP
+
 		if [ "$autooutput" == "false" ]; then
+
 		    x=${#arrfiles[@]}
 		    y=0
 		    echo
@@ -135,8 +150,9 @@ if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
 		        fi
 		    done
 		    echo "Root folder" "${rlt##*/}"
-		    echo  "Press enter for default filename"
-		    read  -p 'Filename or Selection: ' usrslc
+			echo "Press enter for default filename"
+			echo "Filename or Selection:"
+			read usrslc
 		    if [ "$usrslc" != "" ]; then
 		        if [ "$usrslc" -ge 0 ]  2>/dev/null; then
 		            echo selected "$usrslc"
@@ -148,7 +164,7 @@ if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
 		                filename="$appname"
 		            fi
 		        else
-		            filename="$usrslc" #User
+		            filename="$usrslc" #User entered
 		        fi
 		    else
 		        filename="$appname" #Default
@@ -158,9 +174,10 @@ if [ "$SRCDIR" == "SRC" ] && [ "$goahead" == "true" ]; then
 		fi
 
 		fn=$(printf '%b' "$filename") ; fn=$(basename "$fn") ; fn=$(echo "$fn" | sed -E 's/(.*)\.[^./]{3,4}$/\1/') ; fn="${fn// /_}" #fn=$( echo "$fn" | sed -e 's/\...$//' -e 's/\....$//' -e 's/ /_/g')
-        if [ "$fn" != "$appname" ]; then mv /tmp/"$appname".xzm /tmp/"$fn".xzm ; mv /tmp/"$appname"_xdata /tmp/"$fn"_xdata ; fi
-        chown $USR /tmp/"$fn".xzm
-        chown $USR /tmp/"$fn"_xdata
+        if [ "$fn" != "$appname" ]; then mv "/tmp/${appname}.xzm" "/tmp/${fn}.xzm" ; mv "/tmp/${appname}_xdata" "/tmp/${fn}_xdata" ; fi
+		validpdt="true"
+        chown $USR "/tmp/${fn}.xzm"
+        chown $USR "/tmp/${fn}_xdata"
     fi
 fi
 
@@ -205,8 +222,8 @@ fi
 #postop $TMPOPT $0
 
 #Cleanup
-rm -rf $tmp 
-rm -rf $atmp
+test -d "$tmp" && rm -rf "${tmp:?}" 
+test -d "$atmp" && rm -rf "${atmp:?}"
 
 if [ "$validrlt" == "true" ] && [ "$validpdt" == "true" ] && [ "$goahead" == "true" ]; then
     imsg="Your module has been created. in /tmp"
@@ -219,11 +236,12 @@ $imsg
 Total pull range: ${endtm} $chxzm including a file manifest
 EOF
 )
+		cyan "$imsg"
     fi
-    cyan "$imsg"
+    
 fi
-if [ "$validrlt" == "true" ] && [ "$smsg" == "true" ]; then
-    exit 14 
-elif [ "$validrlt" == "false" ]; then
-    exit 7
+if [ "$validrlt" == "true" ] && [ "$smsg" == "true" ]; then  # everything smooth and there is a previous search
+    echo "prev" 
+elif [ "$validrlt" == "false" ]; then  # something went wrong
+    echo "nofiles"
 fi
