Add files via upload

diff --git a/Porteus/usr/local/save-changesnew/start_inotify b/Porteus/usr/local/save-changesnew/start_inotify
--- a/Porteus/usr/local/save-changesnew/start_inotify
+++ b/Porteus/usr/local/save-changesnew/start_inotify
@@ -1,9 +1,27 @@
 #!/usr/bin/env bash
-# supress output helper script to launch inotifywait optional logging   09/15/2025 01/13/2026
+# supress output helper script to launch inotifywait optional logging   09/15/2025 06/21/2026
 #nohup /usr/local/save-changesnew/inotify "$@" > /dev/null 2>&1 &
 SCRIPT_PATH="$( dirname "$0")"
 fmt="%Y-%m-%d %H:%M:%S"
+debug_file=/tmp/inotify.log  # core inotify debug output
+
 log_date=$(date +"$fmt")
-echo $log_date > /tmp/inotify.log
-nohup "$SCRIPT_PATH"/inotify "$@" >> /tmp/inotify.log 2>&1 &
-echo $! > /tmp/inotify_watcher.pid
+echo $log_date > $debug_file
+
+if [ "$#" -lt 8 ]; then
+    echo "Usage: $0 log_file mdlnameprefix cache_file cdir lockfile checksum mode time" >&2
+	echo "not enough args" >> $debug_file
+    exit 1
+fi
+
+nohup "$SCRIPT_PATH"/inotify "$@" "$debug_file" >> $debug_file 2>&1 &
+pid=$!
+sleep 1
+
+if ! kill -0 "$pid" 2>/dev/null; then
+    echo "inotify failed to start" >> $debug_file
+    exit 1
+fi
+
+echo "$pid" > /tmp/inotify_watcher.pid
+
