Add files via upload

diff --git a/Porteus/usr/local/save-changesnew/sysprofile b/Porteus/usr/local/save-changesnew/sysprofile
--- a/Porteus/usr/local/save-changesnew/sysprofile
+++ b/Porteus/usr/local/save-changesnew/sysprofile
@@ -1,23 +1,83 @@
 #!/bin/bash
 shopt -s nullglob										# 9/6/2025
 . /usr/local/save-changesnew/rntchangesfunctions
-atmp=/tmp/ztmp$$ 											;	ch=/mnt/live/memory/images/
-xdata3=$atmp/db_log.log									;	SORTCOMPLETE=$atmp/list_complete_sorted.txt
-md="$1"															;	xdata=$atmp/log.log
+atmp=/tmp/ztmp$$ 						;	ch=/mnt/live/memory/images/
+xdata3=$atmp/db_log.log					;	SORTCOMPLETE=$atmp/list_complete_sorted.txt
+md="$1"									;	xdata=$atmp/log.log
 mkdir $atmp
+mcore() {
+c=$1
+local y=$2
+local folder="$3"
+cmd_base=(xargs -0)
+target_cmd=(/usr/local/save-changesnew/sysprofileloop "$atmp" "$folder" $4)
+if [[ "$md" == "mc" ]]; then
+	if (( c > 1000 )); then
+		y=200 
+		com1=("${cmd_base[@]}")
+		batch_opts=(-n "$y" -P 4)
+		com1+=("${batch_opts[@]}")
+		com1+=("${target_cmd[@]}")
+	elif (( c > 100 )); then
+		y=16
+		com1=("${cmd_base[@]}")
+		batch_opts=(-n "$y" -P 4)
+		com1+=("${batch_opts[@]}")
+		com1+=("${target_cmd[@]}")
+	else
+		y=8
+		com1=("${cmd_base[@]}")
+		batch_opts=(-n "$y" -P 4)
+		com1+=("${batch_opts[@]}")
+		com1+=("${target_cmd[@]}")	
+	fi
+else
+	com1=("${cmd_base[@]}")
+	batch_opts=(-n "$y")
+	com1+=("${batch_opts[@]}")
+	com1+=("${target_cmd[@]}")	
+fi
+"${com1[@]}" < $xdata
+#com1=(xargs -0 -n "${y}" -P 4 /usr/local/save-changesnew/sysprofileloop "$atmp" "$folder")
+#com2=(xargs -0 -n "${y}" /usr/local/save-changesnew/searchfiles "$atmp" "$folder")
+#while IFS= read -r -d '' file; do c="${file#"$folder"}" ; printf '%s\0' "$c" >> "$xdata3" ; done < $xdata
+#find "$dir" -type f -executable -print0 | while IFS= read -r -d '' file; do c="${file#$folder}" ; printf '%s\0' "$c" >> "$xdata3" ; done
+#find "$dir" -type f -executable -print0 | sed -z "s|$folder||g" >> "$xdata3"
+}
+y=50 #default if less than 100 files
+k1="binary"
+k2="sects"
+k3="library"
 for folder in "$ch"{001..003} "$ch"{001..003}-*; do
 	[ ! -d "$folder" ]  && continue
+	#binaryies                  # ! -path '*/usr/share/*' 
 	for subdir in bin etc sbin usr opt/porteus-scripts; do
 		dir="$folder/$subdir"
 		if [ -d "$dir" ]; then
-			if [ "$md" == "mc" ]; then # ! -path '*/usr/share/*' 
-				find "$dir" -type f -executable -print0 | xargs -0 -n 200 -P 4 /usr/local/save-changesnew/sysprofileloop "$atmp" "$folder"
-			else
-				find "$dir" -type f -executable -print0 | while IFS= read -r -d '' file; do c="${file#$folder}" ; printf '%s\0' "$c" >> "$xdata3" ; done
-			fi
+			find "$dir" -type f -executable -print0 > $xdata
+			x=$(tr -cd '\0' < $xdata | wc -c)
+			if (( x > 0 )); then mcore $x $y "$folder" $k1 ;fi
+			
 		fi
 	done
-#	if [ "$md" == "mc" ]; then
+	# configs
+	dir="$folder"/etc
+	if [ -d "$dir" ]; then
+		find "$dir" -type f -print0 > $xdata
+		x=$(tr -cd '\0' < $xdata | wc -c)
+		if (( x > 0 )); then mcore $x $y "$folder" $k2 ; fi
+	fi
+	# *.so*
+	for subdir in $folder/lib $folder/lib64 $folder/usr/lib $folder/usr/lib64 $folder/var/lib $folder/home/guest $folder/~ ; do
+		if [ -d "$subdir" ]; then
+			find "$subdir" -type f -name '*.so*' -print0 > $xdata
+			x=$(tr -cd '\0' < $xdata | wc -c)
+			if (( x > 0 )); then mcore $x $y "$folder" $k3 ; fi
+		fi
+	done
+done
+#Original libraries
+#	if [ "$md" == "mc" ]; then        too few files for mc
 #		for subdir in lib lib64 var/lib; do
 #			dir="$folder/$subdir"
 #			if [ -d "$dir" ]; then 
@@ -26,23 +86,18 @@ for folder in "$ch"{001..003} "$ch"{001..003}-*; do
 #			 fi
 #		done
 #	else#
-#	for subdir in $folder/lib $folder/lib64 $folder/var/lib ; do
-#		if [ -d "$subdir" ]; then
-#			find "$subdir" -type f -name '*.so*' -print0 | while IFS= read -r -d '' file; do c="${file#"$folder"}" ; printf '%s\0' "$c" >> "$xdata3" ; done
-#		fi
-#	done
-# fi
-done
-#x=$(tr -cd '\0' < $xdata | wc -c) ; y=8
+#x=$(tr -cd '\0' < $xdata | wc -c) ; y=8     libs were fewers files so disabled mc originally
 #if (( x > 100 )); then y=16 ; fi
 #if compgen -G "$atmp/searchfiles1_*_tmp.log" > /dev/null; then cat "$atmp"/searchfiles1_*_tmp.log >> "$xdata3"; fi
-if compgen -G "$atmp/searchfiles1_*_tmp.log" > /dev/null; then cat "$atmp"/searchfiles1_*_tmp.log >> "$xdata3"; fi
+if compgen -G "$atmp/${k1}1_*_tmp.log" > /dev/null; then cat "$atmp/$k1"1_*_tmp.log >> "$xdata3"; fi
+if compgen -G "$atmp/${k2}1_*_tmp.log" > /dev/null; then cat "$atmp/$k2"1_*_tmp.log >> "$xdata3"; fi
+if compgen -G "$atmp/${k3}1_*_tmp.log" > /dev/null; then cat "$atmp/$k3"1_*_tmp.log >> "$xdata3"; fi
 sort -o $xdata3 $xdata3
 if [ "$md" == "mc" ]; then
 	x=$(tr -cd '\0' < $xdata3 | wc -c) ; y=8 ; if (( x > 100 )); then y=16 ; fi
 	if ! xargs -0 -n"$y" -P4 /usr/local/save-changesnew/mainloop $atmp $SORTCOMPLETE "/dev/null" "true" < $xdata3; then echo "Error: mainloop or xargs failed" >&2 ; return 2 ; fi
 else
-	if ! xargs -0 /usr/local/save-changesnew/mainloop $atmp $SORTCOMPLETE "/dev/null" "true" < $xdata3; then echo "Error: single mainloop of xargs failed" >&2 ; return 2 ; fi
+	if ! xargs -0 -n 50 /usr/local/save-changesnew/mainloop $atmp $SORTCOMPLETE "/dev/null" "true" < $xdata3; then echo "Error: single mainloop of xargs failed" >&2 ; return 2 ; fi
 fi
 [[ -s "$SORTCOMPLETE" ]] && sed -i '/NOTA-FI-LE 77:77:7/d' $SORTCOMPLETE && echo "$SORTCOMPLETE" || return 1
 #/mnt/live/memory/images/001-core.xzm/usr/lib64/perl5/vendor_perl/XML/Parser/Style/Stream.pm
