Add files via upload

diff --git a/Nemesis/usr/local/bin/recentchanges b/Nemesis/usr/local/bin/recentchanges
--- a/Nemesis/usr/local/bin/recentchanges
+++ b/Nemesis/usr/local/bin/recentchanges
@@ -1,5 +1,5 @@
 #!/bin/bash
-#   NMS5                                                                            08/14/2025  v3.0
+#   NMS5                                                                            08/18/2025  v3.0
 #  
 #   added files that have new atime such as slackpkg to appear in searches
 #   strategically customized output less is more. ie if ANALYTICS and STATPST are off hybrid mode on doesnt appear
@@ -53,7 +53,7 @@ export tmpSRHS=7 # Default 7 store most recent searches in /tmp try 30 and then 
                                 # for hybrid analysis in diff file
                                  # also queries ie recentchanges query stats 
 
-export mMODE="mc"  # normal default. robust less prone to failure
+export mMODE="mem"  # normal default. robust less prone to failure
 								  # mem    balanced store search in arrays less i/o									
 								   # mc      turbo mode run the search in parallel or multiple cores. 
 
@@ -90,7 +90,7 @@ export FEEDBACK="false"  # include find output in terminal as well ie scrolling 
 export checkSUM="true"	# compare file checksums for slight changes
 										# slower useful if you want to check deeper level of stats
 
-export cdiag="true"       # Include stealth changes in diff file    a file was changed but has the same checksum and filesize subtle edit  ie cache items or string was changed
+export cdiag="false"       # Include stealth changes in diff file    a file was changed but has the same checksum and filesize subtle edit  ie cache items or string was changed
 
 export POSTOP="false" # Diagnostics. Create file doctrine. Runs post search operation that can only be done at this time as search is relevant    
                                     # more overhead so recommend off unless one off. output /Downloads  
@@ -132,7 +132,7 @@ passdir=$4
 if [ "$2" == "" ]; then THETIME="noarguser" ; fi
 
 if [ "$3" == "" ] || [ "$4" == "" ]; then 	USR="guest" ; passdir=$PWD ; fi #Default user
-export DISPLAY=:0
+export DISPLAY=:0 # for tkl and root xed featherpad
 export XAUTHORITY=/home/$USR/.Xauthority
 if [ "$3" == "SRC" ]; then echo "Incorrect usage please use recentchanges SRC s , s SRC or SRC" && exit 1; fi #Error handlings
 if  ! id $3 >/dev/null 2>&1; then echo "user:" ${3} "not found"; exit 1; fi # quick user check if called by root recentchanges compile asdfas asdfasd    it could break the script  asdfasd user notfound
@@ -223,7 +223,9 @@ else # Search the default time  5 minutes.
 fi
 fc="find /bin /etc /home /lib /lib64 /opt /root /sbin /usr /var -mmin -${qtn} -not -type d -print0 "
 fca="find /bin /etc /home /lib /lib64 /opt /root /sbin /usr /var \( -cmin -${qtn}-o -amin -${qtn} \) -not -type d -print0"
-if [ "$FEEDBACK" != "true" ]; then eval "$fc" 2> /dev/null | tee $RECENTNUL > /dev/null 2> /dev/null ; $fca 2> /dev/null | tee $toutnul > /dev/null 2> /dev/null ; else eval "$fc" 2>/dev/null ; $fca | tee $toutnul 2> /dev/null ; fi   
+eval "$fc" 2> /dev/null | tee $RECENTNUL > /dev/null 2> /dev/null
+eval "$fca" 2> /dev/null | tee $toutnul > /dev/null 2> /dev/null 
+#else eval "$fc" 2>/dev/null ; eval "$fca" | tee $toutnul 2> /dev/null ; fi   
 
 if [ "$checkSUM" == "true" ]; then cyan "Running checksum. Please wait..."; fi
 if [ "$ANALYTICSECT" == "true" ]; then 
@@ -235,6 +237,7 @@ fi #read -r -p "Press Enter to continue..."
 ###New to version 3
 while IFS= read -r -d '' f; do f="${f//$'\n'/\\n}" ; echo "$f" ; done < $RECENTNUL >> $RECENT # Our main list  with \n escaped to \\n  so we can compare here and also further down
 while IFS= read -r -d '' f; do f="${f//$'\n'/\\n}" ; echo "$f"	; done < $toutnul >> $tout 	
+if [ "$FEEDBACK" == "true" ]; then cat $tout ; cat $RECENT; fi
 if [ -s $tout ]; then grep -Fxv -f $RECENT $tout > $TMPCOMPLETE; fi
 > $tout
 # Slackpkg and pacman download detection ect
@@ -247,7 +250,8 @@ if [ -s $TMPCOMPLETE ]; then
 		declare -a nsf
 		searcharr $xdata # .. array
 	elif [ "$mMODE" == "mc" ]; then
-		xargs -0 -I{} /usr/local/save-changesnew/searchfiles "{}" "$atmp" "$checkSUM" < $xdata
+		#xargs -0 -I{} /usr/local/save-changesnew/searchfiles "{}" "$atmp" "$checkSUM" < $xdata
+		xargs -0 -n8 -P4 /usr/local/save-changesnew/searchfiles "$atmp" "$checkSUM" < $xdata
 		if compgen -G "$atmp/searchfiles1_*_tmp.log" > /dev/null; then cat "$atmp"/searchfiles1_*_tmp.log > $tout; fi
 		if compgen -G "$atmp/searchfiles2_*_tmp.log" > /dev/null; then cat "$atmp"/searchfiles2_*_tmp.log > $COMPLETE; fi
 	else
@@ -650,10 +654,10 @@ if [ -s $SORTCOMPLETE ]; then
         if [ -s $ofile ]; then 
             sort -u -o $ofile $ofile # Built the previous search history
 			cc="$(hanly $SORTCOMPLETE $ofile)"  #hybrid analysis          New to version 3
-			#ret=$?	
-			#if [ $ret -ne 0 ]; then
-			#	red "failure in ANALYTICS hanly subprocess"
-			#fi
+			ret=$?	
+			if [ $ret -ne 0 ]; then
+				echo "failure in ANALYTICS hanly subprocess"
+			fi
         fi        
     fi
     if [ "$STATPST" == "true" ]; then  # STATPST SRG
@@ -668,10 +672,10 @@ if [ -s $SORTCOMPLETE ]; then
 					     if [ -s $ofile ]; then 
 					        sort -u -o $ofile $ofile 
 					   	   	cc="$(hanly $SORTCOMPLETE $ofile)" #hybrid analysis	 and difffile output
-							#ret=$?
-							#if [ $ret -ne 0 ]; then
-							#	echo "failure in STATPST hanyl subprocess"
-							#fi
+							ret=$?
+							if [ $ret -ne 0 ]; then
+								echo "failure in STATPST hanyl subprocess"
+							fi
 					    fi
 						pstc="true"				
 					else
@@ -683,7 +687,7 @@ if [ -s $SORTCOMPLETE ]; then
 			else
 				if [ -s "$pydbpst" ]; then if decrypt "$pydb" "$pydbpst"; then dbc="true"; fi ; fi # # decrypt if any db if we cant decrypt it do nothing to preserve integrity of database. ie we dont make a new one. As we cant merge two dbs
 				[[ ! -s "$pydbpst" ]] && echo Initializing database... && python3 /usr/local/save-changesnew/pstsrg.py --init && dbc="true"  # db empty prepare for next time
-				if [ -s "$pydbpst" ] && [ "$dbc" == "true" ]; then
+				if [ -s "$pydbpst" ] && [ "$dbc" == "true" ]; then # skip first pass
 					# ha database
 					rt="$(python3 /usr/local/save-changesnew/hanlydb.py $SORTCOMPLETE $COMPLETE $pydb $rout $tfile $checkSUM $cdiag)" # Add Nosuchfile we cant ensure no duplicates just add to the count for marking the file
 					ret=$?
