Add files via upload

diff --git a/Nemesis/usr/local/bin/recentchanges b/Nemesis/usr/local/bin/recentchanges
--- a/Nemesis/usr/local/bin/recentchanges
+++ b/Nemesis/usr/local/bin/recentchanges
@@ -45,6 +45,11 @@ export logPRF="del" # del delete and stop    what to do on max logSIZE
 
 export compLVL=200  # default 200mb to disable compression on logpst size
 
+cmode="gzip"                   # default nothing. uses gzip compression level balanced. This is for recentchanges .xzm and SRC tag
+                                           # xz        best compression
+                                           # zstd     faster bootup
+                                            # lzo      faster bootup
+
 export tmpSRHS=7 # Default 7 store most recent searches in /tmp try 30 and then nrun recentchanges query with STATPST false
                                 # for hybrid analysis in diff file
                                  # also queries ie recentchanges query stats
@@ -161,12 +166,11 @@ COMPLETE=$tmp/list_complete.txt							;		RECENTNUL=$tmp/list_recentchanges_filte
 TMPCOMPLETE=$tmp/tmp_complete.txt					;		RSYNCEXCL=$tmp/list_filesexclude.txt
 TMPOPT=$tmp/tmp_holding	                                ;		REJECTLOG=$tmp/list_rejectsrc.txt
 FOLDERLOG=$tmp/save.totalfolders.tmp				;		SORTCOMPLETE=$tmp/list_complete_sorted.txt
-flth=/usr/local/save-changesnew/flth.csv					;		pydbpst=/usr/local/save-changesnew/recent.gpg
-atmp=/tmp/atmp$$												;		slog=/tmp/scr # feedback
-rout=$atmp/routput.tmp										;		xdata=$atmp/logs_stats.log # dcryp log file
-toutnul=$atmp/toutputnul.tmp								;		xdata2=$atmp/logs.log.log # ..
-tout=$atmp/toutput.tmp 										;		THETIME="${arge[0]}" # shift for this script
-USRDIR=/home/$USR/Downloads
+flth=/usr/local/save-changesnew/flth.csv					;		slog=/tmp/scr # feedback
+atmp=/tmp/atmp$$												;		xdata=$atmp/logs_stats.log # dcryp log file
+rout=$atmp/routput.tmp										;		xdata2=$atmp/logs.log.log # ..
+toutnul=$atmp/toutputnul.tmp								;		THETIME="${arge[0]}" # shift for this script
+tout=$atmp/toutput.tmp 										;		USRDIR=/home/$USR/Downloads
 SRCDIR=""
 diffrlt="false"											            ;		pstc="false"
 nodiff="false"											            ;       samerlt="false"
@@ -213,14 +217,14 @@ eval "$fc" 2> /dev/null | tee $RECENTNUL > /dev/null 2> /dev/null
 eval "$fca" 2> /dev/null | tee $toutnul > /dev/null 2> /dev/null
 if [ "$checkSUM" == "true" ]; then cyan "Running checksum. Please wait..."; fi
 if [ "$ANALYTICSECT" == "true" ]; then end=$(date +%s.%N) ; if [ "$checkSUM" == "true" ]; then cstart=$(date +%s.%N) ; fi ; fi
-while IFS= read -r -d '' f; do f="${f//$'\n'/\\n}" ; echo "$f" ; done < $RECENTNUL >> $RECENT
-while IFS= read -r -d '' f; do f="${f//$'\n'/\\n}" ; echo "$f"	; done < $toutnul >> $tout
+while IFS= read -r -d '' f; do f="$( escf "$f")" ; echo "$f" ; done < $RECENTNUL >> $RECENT
+while IFS= read -r -d '' f; do  f="$( escf "$f")" ; echo "$f"	; done < $toutnul >> $tout
 if [ "$FEEDBACK" == "true" ]; then cat $tout ; cat $RECENT; fi
 if [ -s $tout ]; then grep -Fxv -f $RECENT $tout > $TMPCOMPLETE; fi
 > $tout
 #pacman and slaptget Loops
 if [ -s $TMPCOMPLETE ]; then
-	while IFS= read -r x; do x="${x//$'\\n'/\n}"; printf '%s\0' "$x"; done < $TMPCOMPLETE >> $xdata
+	while IFS= read -r x; do  x="$( unescf "$x")"; printf '%s\0' "$x"; done < $TMPCOMPLETE >> $xdata
 	if [ "$mMODE" == "normal" ]; then
 		xargs -0 /usr/local/save-changesnew/searchfiles $atmp $tout $COMPLETE $checkSUM < $xdata
 	elif [ "$mMODE" == "mem" ]; then
@@ -272,7 +276,7 @@ if [ -s $SORTCOMPLETE ]; then
 fi
 /usr/local/save-changesnew/filter $RECENT $USR
 > $tout
-while IFS= read -r x; do x="$(unescf "$x")" ; printf '%s\0' "$x"; done < $RECENT >> $tout
+while IFS= read -r x; do  x="$( unescf "$x")" ; printf '%s\0' "$x"; done < $RECENT >> $tout
 while IFS= read -r -d '' x; do if cp -a --parents "$x" "$tmp$workdir" > /dev/null 2>> $xdata; then printf '%s %s\n' "$x" "success" >> $UPDATE; else echo "Failed to copy: $x" >&2; echo "ERROR: $x" >> $UPDATE; fi; done < $tout
 unset IFS
 if [ -s $xdata ]; then echo > $UPDATE ; cat $xdata $UPDATE; fi
@@ -280,7 +284,7 @@ test -e $xdata && rm $xdata
 echo $BRAND >> $UPDATE
 find $tmp$workdir -not -type d -print0 > $SVFILES
 >$tout
-while IFS= read -r -d '' x; do x="$(escapef "$x")" ; echo "$x" ; done < $SVFILES >> $tout
+while IFS= read -r -d '' x; do x="$( escf "$x")"; echo "$x" ; done < $SVFILES >> $tout
 mv $tout $SVFILES
 sed -i -e "s|$tmp$workdir||g" $SVFILES
 cat $SVFILES | sed -e 's![^/]*$!!g' > $SVFOLDERS
@@ -296,9 +300,10 @@ if [ "$SRCDIR" == "SRC" ]; then
     if [ "$rlt" != "" ]; then
         cat $SVFILES | grep "${rlt}" > $RECENTAPP
         cat $SVFILES | grep -v "${rlt}" > $RSYNCEXCL
-        while IFS= read -r p || [ -n "$p" ]; do p="$(unescf "$p")" ; rm -- "$tmp$workdir$p" ; done < $RSYNCEXCL
-		find $tmp$workdir -type d -empty -delete
-        mksquashfs $tmp$workdir "/tmp/${appname}.xzm"
+        #while IFS= read -r p || [ -n "$p" ]; do p="$(unescf "$p")" ; rm -- "$tmp$workdir$p" ; done < $RSYNCEXCL      Oldway just remove the files But we may want the files to do something else with
+		find $tmp$workdir -type d -empty -delete 
+		while IFS= read -r p || [ -n "$p" ]; do  p="$( unescf "$p")" ; p="${p#/}" ; echo "$p" >> $xdata ; done < $RSYNCEXCL # This is for our SRC files after finding root
+        test -s $xdata && mksquashfs $tmp$workdir "/tmp/${appname}.xzm" -comp $cmode -ef $xdata || { [[ ! -s "$xdata" ]] && mksquashfs $tmp$workdir "/tmp/${appname}.xzm" -comp $cmode ; }
         cp $RECENTAPP "/tmp/${appname}_xdata"
         echo $BRAND >> "/tmp/${appname}_xdata"
         sort -o $RECENTAPP $RECENTAPP
@@ -308,22 +313,30 @@ if [ "$SRCDIR" == "SRC" ]; then
         cat $TMPOPT  | grep -Fvf $RECENTAPP > $TMPCOMPLETE
 	    cd $tmp$workdir || exit
 	    srcpath="${rlt#?}"
-        y=$( wc -l < $RECENTAPP)
-        x=0
-		while IFS= read -r -d '' f ; do f="$(escapef "$f")" ; grep -Fq -- "$f" $RECENTAPP && x=$(( x + 1 )) || { approval="false"; arrreject+=("$f"); } ; done < <(find "${srcpath}" \( -type f -o -type l \) -print0)
+		> $xdata
+		echo rlttt is $rlt
 		r=$( find "${rlt}" -type f | wc -l)  # system count
-		{ echo Root:"${rlt}" ; echo "File count: "$x "of ${y}" ; echo "System count: "$r ; echo ; echo ; } >> "/tmp/${appname}_xdata"                      
-		if [ "$approval" == "true" ]; then
-			{ echo "Status: Complete. Files verified " ; echo ; } >> "/tmp/${appname}_xdata"
+		s=$(grep -n 'MDY' "/tmp/${appname}_xdata" | head -n 1 | cut -d: -f1)
+		if [[ -n "$s" ]]; then s=$(( s - 1 )) ; else s=0 ; fi
+		x=0 # transfer count
+		y=$( wc -l < $RECENTAPP) # What actually made it into /tmp	
+		while IFS= read -r -d '' f ; do echo "$f" >> $xdata ;  x=$(( x + 1 )) ; done < <(find "${srcpath}" \( -type f -o -type l \) -print0)  # Our system files is what we should be comparing		
+		{ echo Root:"${rlt}" ; echo "File count: "$x "of ${y}" ; echo "System count: "$r ; echo ; echo ; } >> "/tmp/${appname}_xdata"   
+		if (( x < y )); then 
+			sort -o $xdata $xdata
+			sort $RECENT > $xdata2
+			comm -23 $xdata1 $xdata2 > $tout
+			{ echo ; echo "Transfer: File transfer failed. " ; echo ; echo "Following file(s) were not transfered:" ; cat $tout ;} >> "/tmp/${appname}_xdata"
+		elif (( x == y)); then
+			{ echo "Transfer: File transfer verified " ; echo ; } >> "/tmp/${appname}_xdata"
 		else
-			{ echo ; echo "Status: Missed base directory. Confirm files or use recentchanges for rntfiles.xzm" ; echo ; echo "Following file(s) do not belong" ; } >> "/tmp/${appname}_xdata"
-            for element in "${arrreject[@]}"; do echo "$element" >> "/tmp/${appname}_xdata"; done
+			{ echo "SRC mode failed. use recentchanges to package application." ; } >> "/tmp/${appname}_xdata"
 		fi
-		{ echo ; echo ; } >> "/tmp/${appname}_xdata"
+		if (( r > s )); then echo "Status: Possibly missed base directory. Confirm files or use recentchanges for rntfiles.xzm." >> "/tmp/${appname}_xdata" ; fi
         echo $BRAND >> $RECENTAPP
-        if [ -s $TMPCOMPLETE ]; then { echo "Items filterout from filtered files."; echo ; cat $TMPCOMPLETE; }  >> "/tmp/${appname}_xdata" ; else echo "No items filtered out from filter."  >>"/tmp/${appname}_xdata" ; fi
+        if [ -s $TMPCOMPLETE ]; then { echo ; echo "Items filterout from filtered files."; echo ; cat $TMPCOMPLETE; }  >> "/tmp/${appname}_xdata" ; else echo "No items filtered out from filter."  >>"/tmp/${appname}_xdata" ; fi
         find "$tmp$workdir$rlt" -type f -print0 > $TMPCOMPLETE
-        while IFS= read -r -d '' f; do f="$(escapef "$f")" ; arrfiles=("${arrfiles[@]}" "${f##*/}"); done < $TMPCOMPLETE
+        while IFS= read -r -d '' f; do  f="$( escf "$f")" ; arrfiles=("${arrfiles[@]}" "${f##*/}"); done < $TMPCOMPLETE
         x=${#arrfiles[@]}
         y=0
         echo ""
@@ -385,7 +398,7 @@ if [ -z "$k" ]; then
     mv $LCLMODULENAME"xSystemchanges"* "/tmp"$moduledir 2> /dev/null ; mv $LCLMODULENAME"xSystemDiffFromLastSearch"* "/tmp"$moduledir 2> /dev/null
     test -e  "/tmp"$MODULENAME"ItemsFilteredout" && rm  "/tmp"$MODULENAME"ItemsFilteredout"
     if [ "$SRCDIR" != "SRC" ]; then # rntfiles.xzm
-	    mksquashfs $tmp$workdir "/tmp"$chxzm
+	    mksquashfs $tmp$workdir "/tmp"$chxzm -comp $cmode
 	    cp $SVFILES "/tmp"$chxzmnm
 	    cp $UPDATE  "/tmp"$MODULENAME"Transferlog"
         if [ "$validrlt" == "true" ]; then
@@ -423,7 +436,7 @@ if [ -s $SORTCOMPLETE ]; then
 			cDATE=$( head -n1 $SORTCOMPLETE | awk '{print $1 " " $2}') #Cut out irrelevant files
             awk -v tme="$cDATE" '$0 >= tme' "$difffile" > $TMPCOMPLETE
 	        echo "          " >> "${difffile}"
-            while IFS="" read -r p || [ -n "$p" ]; do cFILE="$( echo "$p" | cut -d " " -f3-)" ; cFILE=$( escapef "$cFILE") ; grep -Fqs "$cFILE" $SORTCOMPLETE && { echo "Modified" "$p" >> $ABSENT; echo "Modified" "$p" >> $rout; } || { echo "Deleted " "$p" >> $ABSENT; echo "Deleted" "$p" >> $rout; } ;  done < $TMPCOMPLETE
+            while IFS="" read -r p || [ -n "$p" ]; do cFILE="$( echo "$p" | cut -d " " -f3-)" ; grep -Fqs "$cFILE" $SORTCOMPLETE && { echo "Modified" "$p" >> $ABSENT; echo "Modified" "$p" >> $rout; } || { echo "Deleted " "$p" >> $ABSENT; echo "Deleted" "$p" >> $rout; } ;  done < $TMPCOMPLETE
 	        test -f $ABSENT  && { echo Applicable to your search ; cat $ABSENT ; } >> "${difffile}" || { diffrlt="false" ; echo "None of above is applicable to search. It is the previous search."; } >> "${difffile}"
         else
             samerlt="true"
